### ISSUE TITLE
[ВОПРОС]

### ISSUE THREAD

**Issue by socketpair** [lexborisov/myhtml#10]
1. У меня нет инвайта на хабре. ответьте про gumbo - он чётко по спекам, но ЖУТКО медленный, так как оптимизация там не рассматривалась в принципе.
2. Ваш парсер меня интересует для БЫСТРОГО потокового извлечения клеартекста из HTML. Как лучше всего это организовать? другими словами, иерархия дом-элементов меня не интересует, также как и содержимое тега `<head>`.

**Comment by lexborisov** [comment]
Привет!

Если я правильно понял, то интересует исключительно правильная токенизация (определение тегов и их положения), верно?! Парсер у меня тоже чётко по спецификации, иначе никак.

Сейчас я не сохраняю позиции элементов. Причины для этого есть:
Кодировка может прийти любая. Если прилетит UTF-16 то его придется конвертировать до отдачи токенезатору. Соответственно, итоговая разметка не будет совпадать с оригиналом.

Если же вы чётко уверены, что у вас UTF-8 или ASCII на вход то можно подумать и о сохранении позиций. Сохранять позицию не сложно, более того, если нужен только клер-текст  то можно сделать так, чтобы с помощью определенного флага вырубать построение дерева и обработку токенов.

**Comment by socketpair** [comment]
1. Насчёт позиции -- совершенно не понял о чем идет речь.
2. Второе - да, если можно что-то оптимизировать для этой задачи - это было бы ОЧЕНЬ здорово.

Со своей стороны обещаю ревью кода, валгринды, статические анализаторы и проч.

**Comment by lexborisov** [comment]
Договорились, сделаю в ближайшее время поддержку этого функционала.

**Comment by socketpair** [comment]
И я как-бы здесь опять.

**Comment by lexborisov** [comment]
Привет!

Сейчас я активно делаю CSS токенизатор/парсер + Selectors (скоро должено выйти в свет) меня часто дергают, от чего я не успеваю заниматься основной разработкой. На данном этапе мне бы не хотелось надолго отвлекаться. Напиши мне на электронку lex.borisov@gmail.com, обсудим, что ты ожидаешь и что я могу сделать.

**Comment by lexborisov** [comment]
В личной переписке мы это обсуждали. За неимением времени не могу заняться этим. Сейчас работаю над [mycss](https://github.com/lexborisov/mycss)
