### ISSUE TITLE
Compiling under Windows 10 Visual Studio 2017 15

### ISSUE THREAD

**Issue by Randshot** [lexborisov/myhtml#100]
It seems that in the latest release (v4.0.0) CMake support was removed.
I can't seem to find any other way to compile it with VS, or am I missing something?
I tried using NMAKE, but the syntax of the Makefile(s) doesn't seem to be right for that.

**Comment by lexborisov** [comment]
Hi!
You cat try to build with http://www.mingw.org/
or I can create vs solution for build myhtml library
or I can create cmake file :)

**Comment by vtorri** [comment]
@Randshot: as Alex says, you can use MSYS2 + mingw-w64 (not mingw.org, it's an almost dead project) and use the Makefile files. But if you really want to use Visual Studio to compile myhtml, then one has to provide Visual Studio files, or reintroduce cmake files.

**Comment by Randshot** [comment]
I think I managed to compile it with cygwin, but I have two problems.
It seems to only compile a .dll (dynamic library) file, but for my project I would prefer a .lib (static library).
Also, how do I change the MSVCRT?

**Comment by lexborisov** [comment]
@Randshot by default ```make``` create two libraries: shared (*.dll for windows) and static (*.dll.a)
I'm not that good at developing in Windows, @vtorri, please, you can say something about the problem with MSVCRT?
@vtorri promised to create vs solution files for next week, we will be very grateful to him :)

**Comment by Randshot** [comment]
@lexborisov Is there anything special in the Makefiles? Else I could try to just add all the header and source files to a vs project.

**Comment by lexborisov** [comment]
@Randshot all specials for all platform you can see in ```/source/myport/*/Rules.mk``` directory. For Windows is ```/source/myport/windows_nt/Rules.mk```
For normally compile you must add all sources from ```/source/*``` (without ```myport```) and add ```/source/myport/windows_nt/mycore```

The problems should not arise. You must remember that this is a ```C``` project.

**Comment by Randshot** [comment]
@lexborisov I managed to compile a static library (.lib) with VS, but when I try using it within another project, I linking errors :(
```
1>myhtml_static.lib(myhtml.obj) : error LNK2019: unresolved external symbol myencoding_string_append referenced in function myhtml_node_text_set
1>myhtml_static.lib(token.obj) : error LNK2001: unresolved external symbol myencoding_string_append
1>myhtml_static.lib(tree.obj) : error LNK2019: unresolved external symbol mcsync_create referenced in function myhtml_tree_init
1>myhtml_static.lib(mcobject_async.obj) : error LNK2001: unresolved external symbol mcsync_create
1>myhtml_static.lib(mchar_async.obj) : error LNK2001: unresolved external symbol mcsync_create
1>myhtml_static.lib(tree.obj) : error LNK2019: unresolved external symbol mcsync_init referenced in function myhtml_tree_init
1>myhtml_static.lib(mcobject_async.obj) : error LNK2001: unresolved external symbol mcsync_init
1>myhtml_static.lib(mchar_async.obj) : error LNK2001: unresolved external symbol mcsync_init
1>myhtml_static.lib(tree.obj) : error LNK2019: unresolved external symbol mcsync_destroy referenced in function myhtml_tree_destroy
1>myhtml_static.lib(mcobject_async.obj) : error LNK2001: unresolved external symbol mcsync_destroy
1>myhtml_static.lib(mchar_async.obj) : error LNK2001: unresolved external symbol mcsync_destroy
1>myhtml_static.lib(mcobject_async.obj) : error LNK2019: unresolved external symbol mcsync_lock referenced in function mcobject_async_chunk_malloc
1>myhtml_static.lib(mchar_async.obj) : error LNK2001: unresolved external symbol mcsync_lock
1>myhtml_static.lib(mcobject_async.obj) : error LNK2019: unresolved external symbol mcsync_unlock referenced in function mcobject_async_chunk_malloc
1>myhtml_static.lib(mchar_async.obj) : error LNK2001: unresolved external symbol mcsync_unlock
1>myhtml_static.lib(token.obj) : error LNK2019: unresolved external symbol myencoding_string_append_lowercase_ascii referenced in function myhtml_token_node_attr_append_with_convert_encoding
1>myhtml_static.lib(data_process.obj) : error LNK2019: unresolved external symbol myhtml_string_append_chunk_with_convert_encoding_with_preprocessing referenced in function myhtml_data_process_state_ampersand_data
1>myhtml_static.lib(parser.obj) : error LNK2001: unresolved external symbol myhtml_string_append_chunk_with_convert_encoding_with_preprocessing
1>myhtml_static.lib(data_process.obj) : error LNK2019: unresolved external symbol myhtml_string_before_append_any_preprocessing referenced in function myhtml_data_process_state_ampersand_data
1>myhtml_static.lib(parser.obj) : error LNK2001: unresolved external symbol myhtml_string_before_append_any_preprocessing
1>myhtml_static.lib(data_process.obj) : error LNK2019: unresolved external symbol myhtml_string_append_with_preprocessing referenced in function myhtml_data_process_state_ampersand_data
1>myhtml_static.lib(parser.obj) : error LNK2001: unresolved external symbol myhtml_string_append_with_preprocessing
1>myhtml_static.lib(parser.obj) : error LNK2019: unresolved external symbol myhtml_string_append_lowercase_chunk_with_convert_encoding_with_preprocessing referenced in function myhtml_parser_token_data_to_string_lowercase
1>myhtml_static.lib(parser.obj) : error LNK2019: unresolved external symbol myhtml_string_append_lowercase_with_preprocessing referenced in function myhtml_parser_token_data_to_string_lowercase
```

**Comment by lexborisov** [comment]
@Randshot  I think that the problem is that we have a tree-like structure of the project (```/source/myhtml```, ```/source/mycore```), but VS create all object files in one directory and some files are overwritten. For example:
```/source/myencoding/mystring.c``` and ```/source/myhtml/mystring.c``` VS try to create one object file ```/build/Debug/mystring.obj```

This is my guess.

**Comment by Randshot** [comment]
@lexborisov Hm, that could be the problem. Maybe it will help to compile each 'folder' (mycore/myhtml/myencoding) separately?

**Comment by lexborisov** [comment]
@Randshot I do not know VS so good, but maybe it will solve this problem
Welcome to IRC http://webchat.freenode.net/?channels=%23modest-engine :)

**Comment by Randshot** [comment]
@lexborisov It helped a little bit. The 'string' related errors are gone, but there are still some more:
```
4>myhtml_static.lib(tree.obj) : error LNK2019: unresolved external symbol mcsync_create referenced in function myhtml_tree_init
4>mycore_static.lib(mcobject_async.obj) : error LNK2001: unresolved external symbol mcsync_create
4>mycore_static.lib(mchar_async.obj) : error LNK2001: unresolved external symbol mcsync_create
4>myhtml_static.lib(tree.obj) : error LNK2019: unresolved external symbol mcsync_init referenced in function myhtml_tree_init
4>mycore_static.lib(mcobject_async.obj) : error LNK2001: unresolved external symbol mcsync_init
4>mycore_static.lib(mchar_async.obj) : error LNK2001: unresolved external symbol mcsync_init
4>myhtml_static.lib(tree.obj) : error LNK2019: unresolved external symbol mcsync_destroy referenced in function myhtml_tree_destroy
4>mycore_static.lib(mcobject_async.obj) : error LNK2001: unresolved external symbol mcsync_destroy
4>mycore_static.lib(mchar_async.obj) : error LNK2001: unresolved external symbol mcsync_destroy
4>mycore_static.lib(mcobject_async.obj) : error LNK2019: unresolved external symbol mcsync_lock referenced in function mcobject_async_chunk_malloc
4>mycore_static.lib(mchar_async.obj) : error LNK2001: unresolved external symbol mcsync_lock
4>mycore_static.lib(mcobject_async.obj) : error LNK2019: unresolved external symbol mcsync_unlock referenced in function mcobject_async_chunk_malloc
4>mycore_static.lib(mchar_async.obj) : error LNK2001: unresolved external symbol mcsync_unlock
```

**Comment by lexborisov** [comment]
@Randshot You added only one directory from ```/source/myport```? (```/source/myport/windows_nt/mycore```)
It is important! Make sure that only one directory is included in the assembly from ```/source/myport```

**Comment by lexborisov** [comment]
According to the description, he did not add the source code from ```/source/myport/windows_nt/mycore/utils``` or replaced them with something

**Comment by Randshot** [comment]
@lexborisov I solved it my pasting the contents from `myport/windows_nt/mycore/util/mcsync.c` into `mycore/util/mcsync.c` since I didn't want to create another separate project just for this one file. Else it would have overridden the one from mycore.

**Comment by lexborisov** [comment]
@Randshot In the end, everything worked? VS can be teach the tree structures of source code, I read somewhere about it.

**Comment by Randshot** [comment]
@lexborisov That may be the case even though I wouldn't know how ~_~

**Comment by Randshot** [comment]
@lexborisov I will try to throw a solution together some time later.
