### ISSUE TITLE
myhtml_get_nodes: document.querySelector equivalent

### ISSUE THREAD

**Issue by dalibor-drgon** [lexborisov/myhtml#102]
Is there any equivalent of myhtml_get_nodes function for query selector? I want to connect myhtml with mycss and assign styles to each element, but I don't know. Is there any way to achieve this?

**Comment by lexborisov** [comment]
Hi!
Use [Modest](https://github.com/lexborisov/Modest), see [example](https://github.com/lexborisov/Modest/blob/master/examples/modest/selectors_find_nodes_low_level.c) or Modest [example directory](https://github.com/lexborisov/Modest/tree/master/examples/modest)

**Comment by dalibor-drgon** [comment]
Thanks!
