### ISSUE TITLE
Issues building examples on Cygwin

### ISSUE THREAD

**Issue by keithstellyes** [lexborisov/myhtml#105]
#I was able to get the examples to compile and run on my Linux machine, but I had a few issues when trying to install on Cygwin:

**EDIT:** I have solved \#2, and \#1 is solved my pull request. If the pull request gets accepted, this issue can be satisfactorily closed.

\#1. On `make install`, it assumed `/usr/local/include` was a pre-existing directory, once `mkdir /usr/local/include` was called it was fixed.

This pull request fixes it: https://github.com/lexborisov/myhtml/pull/104

~~~\#2. Even still, shared libraries don't seem to be linked correctly?~~~

I fixed it, I just had to add `/usr/lib/` to my `PATH`

~~~Here's an example (same when ran either from `bin/myhtml/` or from `examples/`:~~~

```
$ ./get_title_high_level.exe
C:/cygwin64/home/Keith/git/myhtml/bin/myhtml/get_title_high_level.exe: error while loading shared libraries: libmyhtml-4.dll: cannot open shared object file: No such file or directory
```

**Comment by lexborisov** [comment]
Ok
Pull request #104 has been merged.
Thanks!
