### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [lexborisov/myhtml#11]
I would like to point out that identifiers like "[`MyHTML_TAG__COMMENT`](https://github.com/lexborisov/myhtml/blob/2a445f1a5b983f6e4db194cfd00c4df7d3d2278d/include/myhtml/api.h#L103)" and "[`__tree__`](https://github.com/lexborisov/myhtml/blob/511dc4c403f94cab638168e54f42f205cad2a1d1/include/myhtml/myhtml.h#L65)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by warfish** [comment]
Since this is a pure C99 project i guess this link fits better here: https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier

**Comment by elfring** [comment]
How safe should this software be for the desired data processing by C++ compilers?

**Comment by warfish** [comment]
@elfring This is a good point and i agree with you on the case of leading underscores. However non-leading double underscores seem to be C++-specific limitation which is not in C99 standard. Formally you are correct in a sense that if this header is processed by a C++ compiler it will not be a strictly conforming code, although i personally don't think this is that big of a deal. I guess its up to maintainer.

**Comment by lexborisov** [comment]
I think that to do with it. Change all *__* and all types *_t to something else is not an easy. There are people already using the project.

**Comment by elfring** [comment]
Would you dare a corresponding software transformation so that better standard compliance will be achieved?

**Comment by lexborisov** [comment]
Ok, I will change all *__* in this project

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoid undefined behaviour?")?

**Comment by lexborisov** [comment]
What the issue is exactly, in your opinion?

**Comment by elfring** [comment]
I suggest to reduce deviations from the mentioned standard recommendations. I am unsure if the change acceptance will evolve together with general improvements for your software.

**Comment by lexborisov** [comment]
Do you have any concrete examples of existing deviation from standard recommendations in current code base? Can you point them out so we can fix it?

**Comment by elfring** [comment]
I hope that this bug report can trigger the improvement of the affected identifier selection.
How good can the suggested source code clean-up be achieved by the use of special regular expressions?

**Comment by lexborisov** [comment]
I will do maximum possible for this area

**Comment by lexborisov** [comment]
I'm always using prefixes myhtml_*, MyHTML_*, mycss_*, MyCSS_ I think this is enough.
Thanks for your report!

**Comment by elfring** [comment]
Which commits should [improve the source code](https://github.com/lexborisov/myhtml/blob/19f43083723b332609c475d5634f210ef8115ab3/include/myhtml/myhtml.h#L46 "Update candidate") for this issue?

**Comment by lexborisov** [comment]
I forgot this, now it fixed.
Thank you so much!

**Comment by elfring** [comment]
Thanks for [another source code improvement](https://github.com/lexborisov/myhtml/commit/48cb16e3651239577f85be31ad694e6e3b8e8340 "Deletion of some underscores").

**Comment by lexborisov** [comment]
You are welcome!
