### ISSUE TITLE
Logical error in  myhtml/examples/myhtml/serialization_high_level.c

### ISSUE THREAD

**Issue by DipakGogoi** [lexborisov/myhtml#110]
Hi lex,

Found a small bug in the example which made it non functional.

ln 103
`if(myhtml_serialization_tree_buffer(myhtml_tree_get_document(tree), &str_raw))`

should have been

`if(MyCORE_STATUS_OK == myhtml_serialization_tree_buffer(myhtml_tree_get_document(tree), &str_raw))`

**Comment by DipakGogoi** [comment]
by the way thanks a lot for writing this parser :)

**Comment by lexborisov** [comment]
Hi!
Thanks! Fixed!
