### ISSUE TITLE
Stray <-undef> tag at the beginning of the html file after serialization

### ISSUE THREAD

**Issue by DipakGogoi** [lexborisov/myhtml#111]
Hi Lex,

I don't know if it's a bug or intentional, from my perspective it looks to be a bug.

when using the API - `mystatus_t myhtml_serialization_tree_buffer(myhtml_tree_node_t* scope_node, mycore_string_raw_t* str)`

if argument `myhtml_tree_get_document(tree)` is passed for `scope_node` a stray <-undef> is observed in the serialized html file, this **can be seen with** the **serialization_high_level** example

**Comment by lexborisov** [comment]
This is not a bug, function ```myhtml_tree_get_document``` return ```document``` node it is a root node of tree. For the HTML document, the root node will be ```<HTML>``` tag. Use ```myhtml_tree_get_node_html ```. It is always present in the HTML document and it always a root document.

**Comment by DipakGogoi** [comment]
Hi, Thanks for the reply
I used `myhtml_tree_get_node_html` interface in my code, and it works fine, only thing is I would like to have only `<!DOCTYPE html>` to be in serialization output when using `my_html_tree_get_document` instead of `<-undef><!DOCTYPE html>`, this ensures the serialized html is almost same as the html which was parsed, let me know if there is any other interface, that I have missed.

**Comment by lexborisov** [comment]
@DipakGogoi use myhtml_tree_get_document(tree), it works fine for now, see [example](https://github.com/lexborisov/myhtml/blob/master/examples/myhtml/serialization_high_level.c)

**Comment by DipakGogoi** [comment]
Thanks :)
