### ISSUE TITLE
How to compile the examples?

### ISSUE THREAD

**Issue by Patrickyp** [lexborisov/myhtml#112]
inside myhtml-master/examples/myhtml there are a bunch of example code with the already compiled executable.  I can run the executable fine but how do I compile the sample code myself?  Something like this 

$ gcc get_title_high_level.c 

gets me a bunch of undefined reference to error.

**Comment by lexborisov** [comment]
Hi, @Patrickyp 
For compile all examples just use the command ```make``` in ```myhtml-master```:
```bash
myhtml$ make
...
myhtml$ bin/myhtml/get_title_high_level 
Bad ARGV!
Use: get_title_high_level <path_to_html_file>
```

and see: 
[How to link to a static library in C?](https://stackoverflow.com/questions/1705961/how-to-link-to-a-static-library-in-c)
[Compile a c-program in Linux using shared library](https://stackoverflow.com/questions/29748194/compile-a-c-program-in-linux-using-shared-library)
[Shared libraries with GCC on Linux](http://www.cprogramming.com/tutorial/shared-libraries-linux-gcc.html)

**Comment by Patrickyp** [comment]
This is the command I used and it seems to work.

gcc -I/home/user1/git-repos/myhtml-master/include -L/home/user1/git-repos/myhtml-master/lib/ get_title_high_level.c -o gthl -lmyhtml

Can I ask what example.h is for?

**Comment by lexborisov** [comment]
This is a shared file for examples.
In different OS, the numbers print (see printf function and size_t for windows and linux) differently.
