### ISSUE TITLE
Undeclared identifier "MyHTML_ENCODING_UTF_8"

### ISSUE THREAD

**Issue by ducdetronquito** [lexborisov/myhtml#113]
Hi @lexborisov !

I tried to compile the [example](https://github.com/lexborisov/myhtml#examples) present in `README`, and *gcc* returns me the following error

```c
gcc -L/usr/local/lib -Wall -o test main.c -lmyhtml
main.c: In function ‘main’:
main.c:20:24: error: ‘MyHTML_ENCODING_UTF_8’ undeclared (first use in this function)
     myhtml_parse(tree, MyHTML_ENCODING_UTF_8, html, strlen(html));
```

It seems that `MyHTML_ENCODING_UTF_8` only exists in the `README` and in `devel/osx/osx/main.c:`
```bash
grep -rn "MyHTML_ENCODING_UTF_8"
```

Should `MyHTML_ENCODING_UTF_8` be replaced by `MyENCODING_UTF_8` ?

If it is the case, and if you agree, I can submit a small PR to fix this :)

Ps: Thank you for the time you spend on *Modest* and its related modules :)

**Comment by lexborisov** [comment]
Hi @ducdetronquito !

Thank you for noticing and reporting this! Fixed!
All available encodings can be seen in [this file](https://github.com/lexborisov/myhtml/blob/master/include/myencoding/myosi.h#L46).

P.S.: The development continues and soon (relatively soon) in the project Modest will be a big commit. There will be many improvements :)

**Comment by ducdetronquito** [comment]
Super cool :D !
I would really like to help you when I will be more comfortable coding C.

What is the best way to ask you some questions regarding *MyHTML*/*Modest* internals: issues ? IRC ? *Reddit* ? Don't feel like polluting your maibox ^^

**Comment by lexborisov** [comment]
Thanks!
See [IRC, MAILBOX](https://github.com/lexborisov/Modest#modest--a-pure-c-html-renderer)
Slack: modest-engine.slack.com
Gitter: https://gitter.im/Modest-Engine
