### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ducdetronquito** [lexborisov/myhtml#114]
Hi @lexborisov !

I am sure that you must have a lot of things to work on these days, but I just wanted to open an Issue to discuss about documentation.

I am trying to build a small library on top of *MyHTML* (a fork of [boilerpipe](https://code.google.com/archive/p/boilerpipe/)), and besides the fact that my C skills are pretty thin, I have hard time to understand how things are related inside *MyHTML*.

I think the project would really benefits from some clear documentation on its internals, and on how to use it. The best example I have of a really good documentation is from the [SFML](https://www.sfml-dev.org/documentation/2.4.2/annotated.php) library.

Having a good documentation could be the key to spread *MyHTML*, have more contributions, and moreover to make people more confident to build bindings in their favorite programming language.

For now, do you have any document, schema or anything helpful to understand *MyHTML* internals ?
I would really take some of my time to start some Doxygen documentation of the project when I will feel more confident with C/MyHTML.

Cheers :smile_cat:

**Comment by lexborisov** [comment]
Hi @ducdetronquito !
Lack of documentation is a big problem. What seems obvious for me — to many is a problem.

You are right that I have not enough time for this.

I'll try to describe the architecture, the basic idea of the code. 
There is a description of the functions in [API](https://github.com/lexborisov/myhtml/blob/master/include/myhtml/api.h#L485).

`myhtml/api.h` — is a "public api", you do not have access to structures, everything is done through functions. Perhaps this does not make any sense anymore.
`all other headers (myhtml/*.h)` — we have access to everything, you can change anything.

Your project includes one of two things:
1) `myhtml/api.h`
or 
2) `myhtml/myhtml.h` or `all other headers (myhtml/*.h)`

That is, if you added `api.h` then you can not include other header files.
All the functions in `api.h` are available in `myhtml/myhtml.h` or `other headers (myhtml/*.h)`

**Comment by ducdetronquito** [comment]
I pretty much get it for the distinction between using `myhtml/api.h` and `myhtml/*.h`, thanks to your comments, but I don't quiet get the use case of each data structure.

In a final documentation document it could be great to cover how data structured are related, even if most of the time we can just use `myhtml/api.h`. Do you have document on how data structure are related and what are their purpose ? Could be a good start :)

**Comment by lexborisov** [comment]
@ducdetronquito ,
I will try to describe this in the near future.
