### ISSUE TITLE
Cmake support

### ISSUE THREAD

**Issue by brano543** [lexborisov/myhtml#116]
Hello,

would it be possible to write Cmake build file as it is easier to integrate this library as submodule in project.

Thanks in advance.

**Comment by lexborisov** [comment]
Hi!

I'll think about it. Now it's a modular system, and it needs to be supported in cmake.
It is not difficult at all, but it will take some time.

**Comment by brano543** [comment]
Hello,
i have added the cmake support in #120. Please merge the changes so it is easier to integrate your project as submodule.

**Comment by lexborisov** [comment]
Hi @brano543 

Thanks! Merged!
It remains to support the arguments https://github.com/lexborisov/myhtml/blob/master/Makefile#L21

You can see previous [cmake file](https://github.com/lexborisov/myhtml/blob/caa7d711847c02db8c4dd24855fb1caa8b728a9a/projects/CMakeLists.txt) (removed 21 Mar) 

And there it is necessary to maintain the [modularity of the system](https://github.com/lexborisov/Modest/wiki/Add-new-module)
[This is](https://github.com/lexborisov/myhtml/blob/master/CMakeLists.txt#L11) not good. We must connect all modules in the directory ```source/*``` (myhtml, mycore and other new or removed)
To avoid changing file every time (```CMakeLists.txt```) directory at changing the directory ```source```

**Comment by lexborisov** [comment]
And for a Linux we need add ```add_definitions(-D_POSIX_C_SOURCE=199309L)```

**Comment by brano543** [comment]
I don' t know what am i doing wrong, but when i add_subdirectory, and set up includes, even in target_link_library i add myhtml, still i get undefined reference errors....

**Comment by lexborisov** [comment]
That is, your variant of CMakeLists.txt does not work?
So it must be remade or deleted from the project (until the working version appears).
I could deal with this, but so far this is not a priority for me. If you figure this out will be great.

**Comment by brano543** [comment]
i will try, but i don't know why i get unreferenced symbols, i am sure i include all of the files and the library is linked correctly.

**Comment by brano543** [comment]
I have fixed the cmake build. I didn' t notice i was overriding the variable 3 times, because i didn't put it into single command. #121

**Comment by lexborisov** [comment]
Merged!
But the [question of modularity](https://github.com/lexborisov/myhtml/issues/116#issuecomment-328971045) remained open.

**Comment by brano543** [comment]
The problem is it is difficult to tell cmake to exclude that just one port directory, because you have to choose between the OS. If i just include both of them, it won' t compile, because there will be same definitions for the ported functions.

**Comment by lexborisov** [comment]
@brano543 
[that's](https://github.com/lexborisov/myhtml/blob/master/CMakeLists.txt) what I meant

**Comment by brano543** [comment]
Great job, i just had to fix one typo in the path for ports. You have accidentally went one directory upwards from current cmake source directory. I have fixed that in #122 and it is building just fine

**Comment by lexborisov** [comment]
Have we solved this problem?
At the moment, the cmake (CMakeLists.txt) is available.

**Comment by brano543** [comment]
Hello, I see you have made some changes to the CMakeLists.txt. I will update version of the submodule in my project and let you know if it still works. I have quickly reviewed the changes and it should, but may I ask you for one change though? Could you please rename the arguments 
PROJECT_BUILD_SHARED
PROJECT_BUILD_STATIC
PROJECT_INSTALL_HEADER
to lets say
MYHTML_BUILD_SHARED
MYHTML_BUILD_STATIC
MYHTML_INSTALL_HEADER
so it is more specific to this project and prevent ambiguity between project that may use similar naming?

**Comment by lexborisov** [comment]
Hi!
Ok, no problem, I'm renaming these variables.

**Comment by brano543** [comment]
Ok, after you rename I will test it.

**Comment by lexborisov** [comment]
@brano543 
I renamed this variables, please try it

**Comment by brano543** [comment]
Thank you for changing those variables ! It is working fine, thank you for doing such a great job in improving the CmakeLists I made.
