### ISSUE TITLE
Addition of a build system generator

### ISSUE THREAD

**Issue by elfring** [lexborisov/myhtml#12]
I suggest to reuse a higher level build system than [your current small make file](https://github.com/lexborisov/myhtml/blob/a4bc34553c428d9f21272316cb358999bf8e2d44/Makefile#L1 "Update candidate") so that powerful checks for software features will become easier.
* [CMake](http://cmake.org/ "CMake build system")
* [Autotools](http://www.gnu.org/software/autoconf/#TOCintroduction "GNU build system")

**Comment by lexborisov** [comment]
Hi! Welcome if you can help :), In the near future I will implement it. Thanks for the advice!

**Comment by lexborisov** [comment]
I created [https://github.com/lexborisov/myhtml/blob/master/projects/CMakeLists.txt](CMakeLists.txt) for cmake

**Comment by elfring** [comment]
Thanks for [your addition of a build script](https://github.com/lexborisov/myhtml/commit/480aece89ad0b110e5ae4b4c1e65c57eacab77cb "Introduction of CMake support").
