### ISSUE TITLE
CMake install path

### ISSUE THREAD

**Issue by vallahaye** [lexborisov/myhtml#126]
```
install(DIRECTORY "${PROJECT_DIR_API_HEADER}" DESTINATION "include" FILES_MATCHING PATTERN "*.h")
```

This line in your `CMakeLists.txt` makes CMake install header files in `/usr/local/include/include/` instead of `/usr/local/include`. Consider changing it to :

```
file(GLOB PROJECT_HEADER_DIRS "${PROJECT_DIR_API_HEADER}/*")
foreach(ITEM ${PROJECT_HEADER_DIRS})                                                                                                                                                
    if(IS_DIRECTORY "${ITEM}")
        install(DIRECTORY "${ITEM}" DESTINATION "include" FILES_MATCHING PATTERN "*.h")
    endif()
endforeach()
```
This installs all subdirectories contained in `include` one by one.
Also are you planning on releasing version `4.0.3` (or `4.1`) with all the recent changes ? I'm really looking forward to this so I can rely on a version of your library which supports CMake builds.

Thank you for the time you spend on this and your amazing work. I'm using `myhtml` in one of my project and it rocks !

**Comment by lexborisov** [comment]
Hi!

In fact, it's enough just to put the symbol ```/``` after ```${PROJECT_DIR_API_HEADER}``` like that:
```cmake
install(DIRECTORY "${PROJECT_DIR_API_HEADER}/" DESTINATION "include" FILES_MATCHING PATTERN "*.h")
```
Your option seems to me more correct, I applied it.
Thank you for submitting this bug, and thanks for using myhtml.

**Comment by vallahaye** [comment]
Not sure if it's quiet the same tho as your option would cause CMake to change the output directory permissions (I'm talking about the `/usr/local/include` directory) which is not what you want. Mine does not. Thank you very for your reactivity !

PS: What about my question regarding a potential release date ?

**Comment by lexborisov** [comment]
[Last Release 4.0.4](https://github.com/lexborisov/myhtml/releases/tag/v4.0.4) 12 hour ago.

**Comment by vallahaye** [comment]
Thank you very much ! I'm closing the issue 👍
