### ISSUE TITLE
Cmake pthreads library linking

### ISSUE THREAD

**Issue by vallahaye** [lexborisov/myhtml#127]
```
/usr/local/lib/libmyhtml.so: undefined reference to `pthread_mutex_trylock'
/usr/local/lib/libmyhtml.so: undefined reference to `pthread_join'
/usr/local/lib/libmyhtml.so: undefined reference to `pthread_create'
/usr/local/lib/libmyhtml.so: undefined reference to `pthread_cancel'
collect2: error: ld returned 1 exit status
/usr/local/lib/libmyhtml.so: undefined reference to `pthread_mutex_trylock'
/usr/local/lib/libmyhtml.so: undefined reference to `pthread_join'
/usr/local/lib/libmyhtml.so: undefined reference to `pthread_create'
/usr/local/lib/libmyhtml.so: undefined reference to `pthread_cancel'
collect2: error: ld returned 1 exit status
```
This happens when I try to link my application with `myhtml` when it was built using Cmake. After looking at your `CMakeLists.txt`, I came to the conclusion that you forgot to link `myhtml` targets with the `pthreads` library. Adding `target_link_librairies` directive after lines [189](https://github.com/lexborisov/myhtml/blob/master/CMakeLists.txt#L189) and [195](https://github.com/lexborisov/myhtml/blob/master/CMakeLists.txt#L195) should solve the problem. You can use Cmake module [FindThreads](https://cmake.org/cmake/help/v3.0/module/FindThreads.html) to find out if `pthreads` is installed on the user's operating system.

Thanks in advance.

PS: Again, would it be possible to have a release patching this issue after you're done with it ?

**Comment by lexborisov** [comment]
Hi,
you can send me pull request with this changes?

Thanks!

**Comment by vallahaye** [comment]
Sure ! I'm working on it at the moment. Should the library be built with threads by default ?

**Comment by lexborisov** [comment]
Yes, threads by default. See [L111](https://github.com/lexborisov/myhtml/blob/master/CMakeLists.txt#L111)
[L144](https://github.com/lexborisov/myhtml/blob/master/CMakeLists.txt#L144)
[L149](https://github.com/lexborisov/myhtml/blob/master/CMakeLists.txt#L149)

**Comment by vallahaye** [comment]
Alright, finally is it really that necessary to make a difference between building MyCORE without threads and MyHTML without threads ? I think it would be more correct to have a single option called `MyHTML_BUILD_WITHOUT_THREADS` which turns off building with threads both MyCORE and MyHTML.

**Comment by lexborisov** [comment]
Let it remain as it is. This place will change with time.

**Comment by vallahaye** [comment]
I just created the pull request (#128) so you can review my changes.

**Comment by lexborisov** [comment]
Merged
Thanks!

**Comment by vallahaye** [comment]
Your welcome !
I'm closing the issue 👍
