### ISSUE TITLE
-Wold-style-declaration warnings when compiling with -Wextra

### ISSUE THREAD

**Issue by vallahaye** [lexborisov/myhtml#129]
```c
enum mycore_status {
  ...
}
typedef mycore_status_t;
```
This use of the `typedef` keyword generates `-Wold-style-declaration` warnings when compiling with `-Wextra`. Typedef must be written the following way for the warnings to disappear :
```c
typedef enum mycore_status {
  ...
} mycore_status_t;
```

Have a great day !

**Comment by vallahaye** [comment]
Any news on this issue ?

**Comment by lexborisov** [comment]
Hi!
I missed it. Today-tomorrow I fix it.

**Comment by vallahaye** [comment]
No problem :) ! I'm waiting for your fix.
