### ISSUE TITLE
Complete quoting for parameters of some CMake commands

### ISSUE THREAD

**Issue by elfring** [lexborisov/myhtml#13]
Some parameters (like "[${MyHTML_PROJECT_API_HEADER}](https://github.com/lexborisov/myhtml/blob/480aece89ad0b110e5ae4b4c1e65c57eacab77cb/projects/CMakeLists.txt#L76 "Update candidate")") are passed to CMake commands in your build script without enclosing them by quotation marks. I see that these places will result in build difficulties if the contents of the used variables will contain special characters like semicolons.

I would recommend to apply [advices from a wiki article](http://cmake.org/Wiki/CMake/Language_Syntax#CMake_splits_arguments_unless_you_use_quotation_marks_or_escapes. "CMake splits arguments unless you use quotation marks or escapes.").

**Comment by lexborisov** [comment]
Thanks! I will try to fix all yours comments

**Comment by lexborisov** [comment]
That's all. In this moment there are more priority tasks
