### ISSUE TITLE
Changing modules management

### ISSUE THREAD

**Issue by vallahaye** [lexborisov/myhtml#130]
The idea would be to put each modules (`mycore` `myencoding` ...) into their own repositories and then use [cmake-get](https://github.com/pfultz2/cmake-get) to pull and build modules when needed. `cmake-get` is a pure Cmake implementation of [cget](https://github.com/pfultz2/cget) which allows you to handle dependencies like `npm` or `yarn` would do directly using Cmake. Implementing this solution would let you do versioning on common modules like `mycore` which are copy-pasted in both `myhtml` `mycss` and `Modest`. Tell me what you think about this idea. I'm also open for helping you implementing the solution if you're okay with it.

Thanks in advance.

**Comment by lexborisov** [comment]
Hi! 
Good idea, but Make is a basic build system. It will be difficult to implement this using only Make.

**Comment by vallahaye** [comment]
Yes it would difficult (yet not impossible) to port this functionality to Make but having this as a CMake only feature seems good to me. More over, what's the real advantage in maintaining two ways of building the library ? Now our days CMake is pretty much everywhere so I think going CMake only cleary makes sense 👍 
Maybe we can still keep submodules inside the source folder while still implementing the `cmake-get` solution just as a transition to see what you think of it.

**Comment by vallahaye** [comment]
@data-man It's a question of taste. Those two clearly mark some points but I'm addicted to the fact that thousands of people uses CMake everyday which makes it so easy to find help when needed. Also `myhtml` already uses CMake (and CPack) so I'm not a great fan of replacing it with something else, knowing that the problem (module dependencies) can already easily be solved with CMake.

**Comment by data-man** [comment]
@vallahaye 
Why not provide several ways for the building?
Let users choose what is best for them.

**Comment by vallahaye** [comment]
@data-man You're right, I though you proposed to replace Cmake with premake or tup. I've nothing against having multiple build systems cohabiting 👍
But back to the subject, this issue is about code refactoring and adding dependency management to Cmake which is already in place. Maybe you should open your own issue to request premake build support ?

**Comment by data-man** [comment]
@vallahaye 
> Maybe you should open your own issue to request premake build support ?

Yes, when the repositories will be divided.

**Comment by vallahaye** [comment]
@lexborisov Any news onto this ?

**Comment by lexborisov** [comment]
@vallahaye 
I'm still thinking about this. As soon as I make a decision, I'll write about it here.

**Comment by lexborisov** [comment]
In the current project, nothing will change with the build system. Perhaps I will use this approach in a new project: [lexbor](https://github.com/lexborisov/lexbor).

Thanks!
