### ISSUE TITLE
How to handle various encodings?

### ISSUE THREAD

**Issue by VioletGiraffe** [lexborisov/myhtml#131]
Most web pages on the internet are encoded with UTF-8 nowadays, but not all of them. What is the most efficient way of parsing with the correct encoding? 

The brute force way would be to parse twice: first parse with `MyENCODING_UTF_8`, then look for `<meta charset="XXX">` tag, and if `XXX` is not UTF-8 - parse again with the appropriate encoding. But that seems wasteful. Is there a way to abort parsing from within the `tree_node_insert` callback as soon as I see a non-UTF-8 `charset` attribute?

**Comment by lexborisov** [comment]
Hello!

The specification regulates the behavior in this place. See [spec](https://html.spec.whatwg.org/multipage/parsing.html#determining-the-character-encoding)

Use this code for detect encoding:
```C
/*
 * From Specification:
 *
 * The authoring conformance requirements for character encoding declarations limit them to only 
 * appearing in the first 1024 bytes. User agents are therefore encouraged to use the prescan 
 * algorithm below (as invoked by these steps) on the first 1024 bytes, but not to stall beyond that.
*/
myencoding_t encoding = myencoding_prescan_stream_to_determine_encoding(html, <html_len or first 1024 bytes>);

if(encoding == MyENCODING_NOT_DETERMINED) {
    printf("Can't detect encoding\n");
}
else {
    const char *encoding_name = myencoding_name_by_id(encoding, NULL);
    printf("Encoding: %s\n", encoding_name);
}
```

[See](https://github.com/lexborisov/myhtml/blob/master/source/myencoding/encoding.h#L153)

For detect encoding from `Content-Type` header use:
```C
bool myencoding_extracting_character_encoding_from_charset(const char *data, size_t data_size, myencoding_t *encoding);
```

**Comment by VioletGiraffe** [comment]
Hello, and thank you very much for the great answer! Sorry I didn't notice these functions, I looked in `api.h` but forgot to check the other headers. But I wouldn't understand how to use them anyway without your explanation and the reference to the standard.
