### ISSUE TITLE
Conan package for myhtml

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [lexborisov/myhtml#134]
Hello,
Do you know about [Conan](https://github.com/conan-io/conan)?
[Conan](http://docs.conan.io/en/latest/) is modern dependency manager for C++. And will be great if your library will be available via package manager for other developers.

[Here](https://github.com/bincrafters/conan-templates) you can find example, how you can create package for the library. 

If you have any questions, just ask :-)

**Comment by lexborisov** [comment]
Thank you, I'll look at your project. And I will probably use it in future projects. In the current project, nothing new will be introduced.
