### ISSUE TITLE
Exception at 0x1e34a6, code: 0xc0000005: read access violation at: 0x0, flags=0x0 (first chance)

### ISSUE THREAD

**Issue by donglu** [lexborisov/myhtml#136]
html is: "<p class=\"name\" style=\"padding-left: 5px;\">\n\t\t\t\t\t<a href=\"javascript:;\" class=\"pic\" onclick=\"ToPdfReadBook(13863989,0)\" style=\"font-size: 14px;\" title=\"经济学  微观部分\">《经济学&nbsp;&nbsp;微观部分》\n\t\t\t\t\t</a>\n\t\t\t\t\t\n\t\t\t\t\t\n\t\t\t\t</p>"

when i use             
myhtml_collection_t *text=myhtml_get_nodes_by_tag_id_in_scope(tree,NULL,classname_list->list[i]->child,MyHTML_TAG__TEXT, NULL);
const char *t=myhtml_node_text(text->list[0],NULL);

then error code is show in debug view.
i want to known the reason.Please help me

**Comment by lexborisov** [comment]
I need to know what to contain in `classname_list` and you can check for `NULL` value:
```C
if (classname_list->list[i]->child != NULL) {
    myhtml_collection_t *text = myhtml_get_nodes_by_tag_id_in_scope(tree,NULL,classname_list->list[i]->child,MyHTML_TAG__TEXT, NULL);

    if (text != NULL && text.length != 0) {
        const char *t = myhtml_node_text(text->list[0], NULL);
        /* do what you want */
    }

    myhtml_collection_destroy(text);
}
```

**Comment by donglu** [comment]
classname_list is get as follows:   
myhtml_collection_t *classname_list=myhtml_get_nodes_by_attribute_value(tree,NULL,NULL,false,"class",strlen("class"),"name",strlen("name"),NULL);
it's not NULL.

**Comment by lexborisov** [comment]
This code work fine:

```C
    const char* data = "<p class=\"name\" style=\"padding-left: 5px;\">\n\t\t\t\t\t<a href=\"javascript:;\" class=\"pic\" onclick=\"ToPdfReadBook(13863989,0)\" style=\"font-size: 14px;\" title=\"经济学 微观部分\">《经济学  微观部分》\n\t\t\t\t\t\n\t\t\t\t\t\n\t\t\t\t\t\n\t\t\t\t";
    
    myhtml_t* myhtml = myhtml_create();
    myhtml_init(myhtml, MyHTML_OPTIONS_DEFAULT, 2, 0);
    
    myhtml_tree_t* tree = myhtml_tree_create();
    myhtml_tree_init(tree, myhtml);
    
    myhtml_parse(tree, MyENCODING_UTF_8, data, strlen(data));
    
    myhtml_collection_t *classname_list = myhtml_get_nodes_by_attribute_value(tree, NULL, NULL, false, "class", strlen("class"), "name", strlen("name"), NULL);
    
    for (size_t i = 0 ; i < classname_list->length; i++) {
        myhtml_collection_t *text = myhtml_get_nodes_by_tag_id_in_scope(tree, NULL, classname_list->list[i], MyHTML_TAG__TEXT, NULL);
        
        for (size_t j = 0 ; j < text->length; j++) {
            const char *t = myhtml_node_text(text->list[j], NULL);
            printf("%s\n", t);
        }
        
        myhtml_collection_destroy(text);
    }
    
    myhtml_collection_destroy(classname_list);
    
    myhtml_tree_destroy(tree);
    myhtml_destroy(myhtml);
```

in `myhtml_get_nodes_by_tag_id_in_scope` not child, this is scope node.

**Comment by donglu** [comment]
Problem solved, Thanks!

**Comment by donglu** [comment]
another problem, the code as follows:
    const char* data = "<p class=\"name\" style=\"padding-left: 5px;\"> <a href=\"javascript:;\" class=\"pic\" onclick=\"ToPdfReadBook(13863989,0)\" style=\"font-size: 14px;\" title=\"经济学 微观部分\">《经济学&nbsp;&nbsp;微观部分》 </a> </p>";

    myhtml_t* myhtml = myhtml_create();
    myhtml_init(myhtml, MyHTML_OPTIONS_DEFAULT, 2, 0);

    myhtml_tree_t* tree = myhtml_tree_create();
    myhtml_tree_init(tree, myhtml);

    myhtml_parse(tree, MyENCODING_UTF_8, data, strlen(data));

    myhtml_collection_t *classname_list = myhtml_get_nodes_by_attribute_value(tree, NULL, NULL, false, "class", strlen("class"), "name", strlen("name"), NULL);

    for (size_t i = 0 ; i < classname_list->length; i++) {
        myhtml_collection_t *text = myhtml_get_nodes_by_tag_id_in_scope(tree, NULL, classname_list->list[i], MyHTML_TAG__TEXT, NULL);

        for (size_t j = 0 ; j < text->length; j++) {
            const char *t = myhtml_node_text(text->list[j], NULL);
            printf("%s\n", t);
        }

        myhtml_collection_destroy(text);
    }

    myhtml_collection_destroy(classname_list);

    myhtml_tree_destroy(tree);
    myhtml_destroy(myhtml);

the result is 《经济学聽聽微观部分》, but my need data is 《经济学&nbsp;&nbsp;微观部分》.
how to solve it?

**Comment by lexborisov** [comment]
I do not understand, in your example there is no `《经济学聽聽微观部分》` data.
I run your example and get result: `《经济学  微观部分》`
