### ISSUE TITLE
<-undef> in serialization and lost doctype content

### ISSUE THREAD

**Issue by Azq2** [lexborisov/myhtml#139]
I have some strange html:
```
<!-- wsefwefewf --><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
		<div>fwew<a href="" test data-xuj="1" ololo="1">wefwef</a>, <a href="q">we <b>bbb</b> fwef</a>, <a href="">wefwef</a>, <a href="z">wefwef</a>efwef</div>
```

And it parsed with default options:
```
status = myhtml_init(self->myhtml, MyHTML_OPTIONS_DEFAULT, 1, 0);
....
status = myhtml_parse(tree, MyENCODING_UTF_8, html_str, html_length);
```

And i will try to serialize full document:
```
myhtml_tree_node_t *node = myhtml_tree_get_document(tree);
myhtml_serialization_tree_callback(node, sv_serialization_callback, RETVAL);
```

And i get strange token `<-undef>`  in output:
```
$VAR1 = '<-undef><!DOCTYPE html><html><head></head><body><div>fwew<a href="" test="" data-xuj="1" ololo="1">wefwef</a>, <a href="q">we <b>bbb</b> fwef</a>, <a href="">wefwef</a>, <a href="z">wefwef</a>efwef</div>
	</body></html>';
```

1. may be, myhtml_serialization_tree_callback should not serialize MyHTML_TAG__UNDEF
2. i think, main issue - document node has tag_id == MyHTML_TAG__UNDEF
May be, need new MyHTML_TAG__DOCUMENT for document node. 
3. Where content of doctype?
I tried manualy use `myhtml_node_text()`, but got empty string.

**Comment by lexborisov** [comment]
Hm,
my code:
```C
    myhtml_t* myhtml = myhtml_create();
    myhtml_init(myhtml, MyHTML_OPTIONS_DEFAULT, 1, 0);
    
    myhtml_tree_t* tree = myhtml_tree_create();
    myhtml_tree_init(tree, myhtml);
    
    myhtml_parse(tree, MyENCODING_UTF_8, html, size);

    mycore_string_raw_t str = {0};
    myhtml_serialization_tree_buffer(myhtml_tree_get_document(tree), &str);
    printf("%s\n", str.data);
    
    myhtml_tree_destroy(tree);
    myhtml_destroy(myhtml);
```

I got result:
```HTML
<!-- wsefwefewf --><!DOCTYPE html><html><head></head><body><div>fwew<a href="" test="" data-xuj="1" ololo="1">wefwef</a>, <a href="q">we <b>bbb</b> fwef</a>, <a href="">wefwef</a>, <a href="z">wefwef</a>efwef</div></body></html>
```
Let's see what the difference is...

**Comment by lexborisov** [comment]
Perhaps something forgot to update. I can do diff for source/myhtml dir, or you if wont.

**Comment by Azq2** [comment]
Ok, may be later i can try fix this
A long time watching the project and always interested in one question... Why git submodules not used?

**Comment by lexborisov** [comment]
Difficult question
There were different ideas that are not relevant now

See [story](https://medium.com/@lex.borisov/browser-browser-engine-35d2fb18eb07) list to `Something about Modest`

**Comment by lexborisov** [comment]
I have a new project on the way. The quality of the code, the ideas, everything is new.

**Comment by Azq2** [comment]
doctype fixed in https://github.com/lexborisov/myhtml/pull/151
