### ISSUE TITLE
Invalid parsing of malformed char references

### ISSUE THREAD

**Issue by Azq2** [lexborisov/myhtml#149]
Source:
``` &quo &redirect ```

Text content in myhtml:
``` " ®direct ```

Text content in browser (expected):
``` &quo &redirect ```

**Comment by Azq2** [comment]
https://github.com/lexborisov/myhtml/pull/150

**Comment by Azq2** [comment]
Probaly fix 2.0 https://github.com/lexborisov/myhtml/pull/152

**Comment by lexborisov** [comment]
Thanks for PR!
Your solution has fixed the problem!
