### ISSUE TITLE
Issue with scope node

### ISSUE THREAD

**Issue by adtrevor** [lexborisov/myhtml#167]
When parsing this HTML snippet:
```html
<!DOCTYPE html>
    <html>
        <head>
            <title>Foo</title>
            <meta charset="utf-8">
        </head>
        <body>
            <div id="firstDiv">
                <p class="foo bar">Hey</p>
                <p class="baz bar">Cools</p>
            </div>
            <p></p>
            <div></div>
            <div id="hey" class="amazing bar"></div>
            <img src="automn.jpg" hidden>
        </body>
    </html>
```

A call to:
```c
myhtml_get_nodes_by_attribute_value_end(tree,NULL, div, false, idStr, idStrCount, barStr, barStrCount, NULL)
```
_Here, `div` is my "firstDiv" node, `idStr` is a string that contains `"id"` value, and `barStr` is a string that contains `"bar"`_

**MyHTML returns 3 nodes instead of 2 as I would have expected since I reduced the scope to a node that only contains two such nodes.**

Could this be a bug or do you think I'm doing something wrong?

Thank you

**Comment by 1aam2am1** [comment]
You have 3 nodes there:
 * p node
 * p node
 * text node

**Comment by adtrevor** [comment]
@1aam2am1 Yes, but only two nodes with class containing var, isn't it?

**Comment by adtrevor** [comment]
And actually, shouldn't it be 4 nodes, in that case? (if text nodes are taken into account)

**Comment by 1aam2am1** [comment]
I actually from sometime don't write in this library. But you could write the collection nodes to output and see what it have collected. If it have collected everything ok. Then ok, when not then you can see where is error.

**Comment by adtrevor** [comment]
@1aam2am1 I checked the nodes that are returned and the three nodes are indeed two `p` and one `div`, more precisely:
```html
<p class="foo bar">Hey</p>
<p class="baz bar">Cools</p>
<div id="hey" class="amazing bar"></div>
```

So it does seem like there is a bug :/

**Comment by 1aam2am1** [comment]
Then check what is the div node that you pass down to function if it really is firstdiv then bug if not then it is node that have the 3 nodes in it. You can also try write tree. Whatching if it was parset correctly.

**Comment by adtrevor** [comment]
@1aam2am1 The scope node is indeed `<div id="firstDiv">`, so there is a bug, except if I missed something else.

**Comment by 1aam2am1** [comment]
I can't see bug in code. Well print tree and watch if it is good parset. If it is then only @lexborisov can help.

**Comment by lexborisov** [comment]
@adtrevor @1aam2am1 
Fixed. Please, try.

**Comment by adtrevor** [comment]
@lexborisov That fixes it! Thank you so much! 🎉
