### ISSUE TITLE
JS `nodeType` equivalent?

### ISSUE THREAD

**Issue by adtrevor** [lexborisov/myhtml#168]
Hello,
Is there anything enabling to get the type of a node as with JS `nodeType`? I can't find it unfortunately.

Thank you

**Comment by adtrevor** [comment]
Apparement aucun, il faudrait passer par le `tagId` et, en se basant sur https://github.com/lexborisov/myhtml/blob/master/source/myhtml/tag_const.h obtenir une fonctionnalité similaire.

**Comment by lexborisov** [comment]
In MyHTML there is no concept of a node type. Everything is determined by tag id.
For example,
```
text => MyHTML_TAG__TEXT
comment => MyHTML_TAG__COMMENT
doctype => MyHTML_TAG__DOCTYPE
```

I highly recommend that you use a [lexbor HTML](https://lexbor.com/docs/lexbor/html/) parser. This is a modern and very fast parser (like a myhtml).
Please, see [examples](https://github.com/lexbor/lexbor/tree/master/examples/lexbor/html). Lexbor HTML have a [node type](https://github.com/lexbor/lexbor/blob/master/source/lexbor/dom/interfaces/node.h#L22).

**Comment by adtrevor** [comment]
@lexborisov That's interesting, I think MyHTML currently is right for my current project, but in the future I'd be happy to try Lexbor. In the meantime I think tag id will be enough for my needs.

Thank you!

**Comment by adtrevor** [comment]
@lexborisov Do you think I'm doing something wrong in #167 ?
