### ISSUE TITLE
Custom tags in html

### ISSUE THREAD

**Issue by Notevill** [lexborisov/myhtml#174]
Извините, плохо умею в английский.
Немного я помучался, и ничего не получилось. Правильно ли я понял, что myhtml плохо работает с не html тегами в html документе. 
К примеру у меня есть вот такая структура в html документе.
```
<reporttemplate>
          <query sqltext="SELECT TOP 10 @Number, @Date, @Name, @State From NameStates Where @Date <= @SetDate" >
            <param name = "@Date" substring="Date" type = "DateTime" />
            <param name = "@Name" substring="Value" type = "string" />
            <param name = "@State" substring="State" type = "string" />
            <param name = "@Number" substring="Number" type = "int" />
            <filter name = "@SetDate" substring="10-03-19 13:23:00" type = "DateTime" />
          </query>
          <template>
            <tr>
              <td>@Date</td>
              <td>@Name</td>
              <td>@State</td>
            </tr>
          </template>
        </reporttemplate>
```
через myhtml_get_nodes_by_name я могу получить элемент в дереве, но например myhtml_node_string(node) - возвращает непонятную строку вида ``"\n            "``. То же самое возвращается если попробовать myhtml_serialization_node_callback. 

Идея была такая, чтобы получить reporttemplate, пробежаться по его child, и сравнивая теги по имени сделать дальнейшую обработку.

**Comment by Notevill** [comment]
Поправка оказывается все работает почти как ожидалось. Вопрос оказался в другом.
Написал такую функцию:
```
// получение имени тега по ноду
QString GetTagName(myhtml_tree_t *tree, myhtml_tree_node_t *node){
     const char *tag_name = myhtml_tag_name_by_id(tree, myhtml_node_tag_id(node), nullptr);
     return tag_name;
}
```
Если туда передать node, который находится через myhtml_get_nodes_by_name, то все работает как и ожидалось. Но если передать туда его child, то получаем   ``"\n "``. Теперь вопрос куда указывает node полученный через myhtml_node_child?

**Comment by lexborisov** [comment]
@Notevill 
Привет!

Всё верно, функция `myhtml_node_child ` указывает на `child`. Не забывайте, что пробелы, новые строки и табы всё это тоже нода.

Для примера:
 ```HTML
<div>
    <a>text</a>
```

Итоговое дерево будет такого вида:
```HTML
<div>
    "\n    "
    <a>
        "text"
```

То есть, видим, что первый чайлд у ноды `div` будет текст с новой строкой и пробелами, а второй нода `a`.

**Comment by Notevill** [comment]
Я правильно понимаю, что если перед <a> несколько пробелов, то все они будут отдельными нодами? То есть чтобы добраться от <div> до <a>, нужно получить один child, и несколько раз next? 
Если использовать MyHTML_TREE_PARSE_FLAGS_SKIP_WHITESPACE_TOKEN, то такой проблемы нет.  Но если мы хотим модифицировать html, то на выходе у нас получится человеко-нечитаемый формат?.
Эта вещ с распарсиванеим дерева вида 
```` html
  <div>
    "\n    "
    <a>
        "text"
````
Не совсем очевидна, почитал другие Issues, и заметил, что у разных людей в разных задачах возникает такая проблема.
