### ISSUE TITLE
Undefined symbols for architecture x86_64:

### ISSUE THREAD

**Issue by jules23** [lexborisov/myhtml#178]
Hi! 

I installed according to the instructions, then copied and pasted one of the examples, and I get the error below.

I am compiling with gcc, and I am on MacOS.
Any help is greatly appreciated!

Undefined symbols for architecture x86_64:
  "_myhtml_attribute_add", referenced from:
      _main in hello-7f1bec.o
  "_myhtml_attribute_by_key", referenced from:
      _main in hello-7f1bec.o
  "_myhtml_attribute_delete", referenced from:
      _main in hello-7f1bec.o
  "_myhtml_attribute_value", referenced from:
      _main in hello-7f1bec.o
  "_myhtml_collection_destroy", referenced from:
      _main in hello-7f1bec.o
  "_myhtml_create", referenced from:
      _main in hello-7f1bec.o
  "_myhtml_destroy", referenced from:
      _main in hello-7f1bec.o
  "_myhtml_get_nodes_by_name", referenced from:
      _main in hello-7f1bec.o
  "_myhtml_init", referenced from:
      _main in hello-7f1bec.o
  "_myhtml_parse_fragment", referenced from:
      _main in hello-7f1bec.o
  "_myhtml_serialization_tree_callback", referenced from:
      _main in hello-7f1bec.o
  "_myhtml_tree_create", referenced from:
      _main in hello-7f1bec.o
  "_myhtml_tree_destroy", referenced from:
      _main in hello-7f1bec.o
  "_myhtml_tree_get_node_html", referenced from:
      _main in hello-7f1bec.o
  "_myhtml_tree_init", referenced from:
      _main in hello-7f1bec.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by lexborisov** [comment]
@jules23 
Sorry, I skipped this issue. It looks like you didn’t link the library when linking. `-lmyhtml`
