### ISSUE TITLE
How to get HTML source of myhtml_tree_node?

### ISSUE THREAD

**Issue by vaibhavpandeyvpz** [lexborisov/myhtml#180]
How do we get the HTML source for one particular node? I am able to get the text content with `myhtml_node_text` on child node but can't figure out a way for HTML?

**Comment by lexborisov** [comment]
@vaibhavpandeyvpz 

Please, see [example](https://github.com/lexborisov/myhtml/blob/master/examples/myhtml/serialization_high_level.c).
