### ISSUE TITLE
Header files duplicated - why?

### ISSUE THREAD

**Issue by f2404** [lexborisov/myhtml#21]
The header files are duplicated in the source/myhtml/ and include/myhtml/ directories. What is the reason for that?

**Comment by lexborisov** [comment]
Hi, Igor! 

Initially, the directory "include/html/" contained only api.h - public api. This API makes it impossible to directly control structures, only through the function. At the beginning of the development of this file was not in the "source/myhtml/". Currently i'm trying to divide developer version from the public api.

**Comment by lexborisov** [comment]
at the same time I want to keep the possibility of embeddable sourse/myhtml

**Comment by f2404** [comment]
Hi lex (Alex?),
I can see your point in dividing the headers into public and private sets. But I still don't think the files have to be duplicated in different locations...

**Comment by lexborisov** [comment]
You're right, but I want to somehow divide the place for clarity

Alex

**Comment by xor-gate** [comment]
For linux kernel code to have public API headers only this process is called: "kernel header sanitizing". Probably this can be done with a tool like here: https://github.com/fanf2/unifdef  . It seems NetBSD kernel developers use this to create public kernel API headers from a shared header.

**Comment by lexborisov** [comment]
In Release version "include" directory will be deleted. And "include" directory will be deleted from the [mycss](https://github.com/lexborisov/mycss)
