### ISSUE TITLE
source/myhtml/Makefile issue

### ISSUE THREAD

**Issue by nwmcsween** [lexborisov/myhtml#22]
Didn't bother doing a PR as it's simple:
In source/myhtml/Makefile CFLAGS should be
CFLAGS ?= -Werror ...
CFLAGS += -fPIC -std=c99 ...
since if a user sets CFLAGS to something else the project will still compile.

**Comment by lexborisov** [comment]
Thanks! I fix it tomorrow

**Comment by lexborisov** [comment]
Done! Thanks! for your report
