### ISSUE TITLE
Can the tree node expose its position and size?

### ISSUE THREAD

**Issue by fabiofumarola** [lexborisov/myhtml#24]
This would be useful to check the position of parsed elements

**Comment by lexborisov** [comment]
Hi!
What the position do you mean?

**Comment by fabiofumarola** [comment]
Hi, I tried your examples and look interesting, but question is related to css parsing and DOM layering. Is it possible to got for each DOM node position and size?

**Comment by lexborisov** [comment]
I'm sorry, but when it comes to CSS position and size? then they do not exist, it is only a parser. CSS and Render will appear later (I can not say exactly when, but it will)
