### ISSUE TITLE
SAX parser

### ISSUE THREAD

**Issue by kostya** [lexborisov/myhtml#26]
Is there any way to do sax parsing, without building tree?

**Comment by lexborisov** [comment]
Hi!

You are interested only XML (not HTML)? Now you can receive tokens in the stream (without constructing a tree), but it requires a bit of programming.

**Comment by kostya** [comment]
html also (something like libxml html sax parser), 
another question, if in the page no closed tag, would it autoclosed as libxml does?

**Comment by lexborisov** [comment]
Firstly, you can not correctly parse html without build tree.
Better than libxml. This parser (myhtml) fully conformant with the HTML5 specification. The result of parsing is the same as in modern browsers.
