### ISSUE TITLE
content after body parsed as in body

### ISSUE THREAD

**Issue by kostya** [lexborisov/myhtml#31]
```html
<html>
<body>

<a href=#1>A1</a>

</body>

<a href=#2>A2</a>
</html>
```

```
(html(head)(body(a(href#1 '#1'))(a(href#2 '#2'))))
```

**Comment by lexborisov** [comment]
That's right!

The specification states [parsing after body](https://html.spec.whatwg.org/multipage/syntax.html#parsing-main-afterbody) (see "Anything else")

as all modern browsers
