### ISSUE TITLE
memory usage is pretty big

### ISSUE THREAD

**Issue by kostya** [lexborisov/myhtml#32]
7.5 Mb html file, used to parse 124Mb RSS.

maybe there is some ways(options) to reduce number of nodes, for example not create empty (whitespaced) text node, which is almost half of all the nodes.

**Comment by lexborisov** [comment]
Can see the file?
In general, today-tomorrow will be a big update. It aims to decrease memory consumption and speed up parsing.

**Comment by lexborisov** [comment]
It can be an option, but it would be contrary to the specifications

**Comment by kostya** [comment]
https://www.dropbox.com/s/nfno8ef25j4cu4m/test_large_4.html?dl=0

**Comment by lexborisov** [comment]
Here it is difficult to do something. In the Middle different all parsers ~100MB (+-10MB).
I can add an option - not to create empty tokens.

**Comment by kostya** [comment]
also sax parser can save much more memory.

**Comment by lexborisov** [comment]
If you need to correctly parse and create tree the html a sax parsers will not help. Decide that you need.

**Comment by kostya** [comment]
please add options to skip whitespaced texts

**Comment by lexborisov** [comment]
With pleasure. Tomorrow evening will be ready

**Comment by kostya** [comment]
can you please explain what is stored in node?
tag_name, attrbiutes, text - is stored fully, or just as pointer and length on original string?

**Comment by lexborisov** [comment]
No, not original. Any input text that is in need of preprocessing. For this reason, you can not just keep a pointer to the original. This applies to many things:
[consume a character reference](https://html.spec.whatwg.org/multipage/syntax.html#consume-a-character-reference)
[replace for attribute name U+0000 NULL](https://html.spec.whatwg.org/multipage/syntax.html#after-attribute-name-state)
[preprocessing the input stream](https://html.spec.whatwg.org/multipage/syntax.html#preprocessing-the-input-stream)
and other replaces [parsing main in foreign: MathML and SVG](https://html.spec.whatwg.org/multipage/syntax.html#parsing-main-inforeign)

**Comment by lexborisov** [comment]
And I remember that I had promised to make the option to not save whitespace tokens. Be sure to do

**Comment by kostya** [comment]
why you can not process it on the fly? when you requesting for example attribute for node it processed, if no requested, just stored only pointer and length

**Comment by lexborisov** [comment]
It is much more complicated. Doing as you described is bad. At a minimum, the code will become unreadable. Now a single place of memory. You offer to arrange a mess at this point.

P.S.: If you write in Russian do not hesitate to write to the email, will be easier to communicate

**Comment by kostya** [comment]
тогда все равно не понятно откуда берется столько памяти

7.5Mb - копия всех текстов
1.4Mb - 352851 нод - каждая хранит tag_id (4 byte) 
1.4Mb - 352851 нод - каждая хранит count аттрибутов(4 byte) 
224Kb - 56078 аттрибутов - каждый хранит длину (4 byte)
785Kb - 196304 текстовых нод - каждая хранит длину 4byte
2.8Mb - 352851 нод каждая хранит два поинтера 8 byte

итого дерево должно примерно весить: 15Mb

**Comment by lexborisov** [comment]
See tree.h, token.h, thread.h
One Tree node: 
```C
struct myhtml_tree_node {
    enum myhtml_tree_node_flags flags;
    
    myhtml_tag_id_t tag_idx;
    enum myhtml_namespace my_namespace;
    
    myhtml_tree_node_t* prev;
    myhtml_tree_node_t* next; 
    myhtml_tree_node_t* child; 
    myhtml_tree_node_t* parent; 
    myhtml_tree_node_t* last_child;

    myhtml_token_node_t* token;
};
```
