### ISSUE TITLE
50K non closed divs parsed too slow

### ISSUE THREAD

**Issue by kostya** [lexborisov/myhtml#33]
```
page = "<div>" * 50_000
parser = Myhtml::Parser.new
parser.parse(page)
```
4.8s

but 50K span is fast.
```
page = "<span>" * 50_000
parser = Myhtml::Parser.new
parser.parse(page)
```
0.01s

**Comment by lexborisov** [comment]
This synthetic benchmark. It copes fast. For example, html5ever 71 sec, gumbo 55 sec (and 3247284224 mem O_o)

**Comment by kostya** [comment]
libxml in sax mode, 0.09s

**Comment by lexborisov** [comment]
Again, this is not the SAX parser. This is fully conformant with the HTML5 specification. All for the correct processing of html.

Non closed tags is normal situation, but this test is synthetic. The HTML specification is such that you can think of a lot of synthetic tests in which everything will run slowly. Try to open the test in a browser -- very, very long time of result

**Comment by kostya** [comment]
ok, thanks

btw, why span is much faster? something special with div?

**Comment by lexborisov** [comment]
Different algorithms processing elements. [Special](https://html.spec.whatwg.org/multipage/syntax.html#special) or [Ordinary](https://html.spec.whatwg.org/multipage/syntax.html#ordinary)

See [in body](https://html.spec.whatwg.org/multipage/syntax.html#parsing-main-inbody) "A start tag whose tag name is one of: ..., "div",..." and "Any other start tag"
