### ISSUE TITLE
Backwards compatibility 

### ISSUE THREAD

**Issue by pedro93** [lexborisov/myhtml#34]
Does this library provide support for older HTML specifications?
Is it in the roadmap? 
If not what is the default treatment of html elements like:
```html
<title>A Tutorial: <![CDATA[<!-- HTML Comments -->]]></title>
```

Thanks and congratulations on what seems to be an amazing project!

**Comment by lexborisov** [comment]
Hi!
Thank you!

HTML Specification supported CDATA only for not HTML Namespace elements: SVG and Math. You probably mean XHTML? Development XHTML long been discontinued and I, like everyone else, I see no reason to support it.

For example:
```html
<div>
<math>A Tutorial: <![CDATA[<!-- HTML Comments -->]]></math>
</div>
```

Parser (and all modern browsers) return:
```html
<html>
	<head>
	<body>
		<div>
			<-text>
			<math>
				<-text>: A Tutorial: <!-- HTML Comments -->
			<-text>
```

**Comment by pedro93** [comment]
So that would mean the data structure in the parser would have something like:
element(math).child[0] == textNode(": A Tutorial: ")
element(math).child[0] == commentNode("")?

P.S: Disregard the structure :P

**Comment by lexborisov** [comment]
Will be created one child:
element(math).child[0] == textNode("A Tutorial: ")

**Comment by pedro93** [comment]
ok, thanks! you may now close the issue

**Comment by lexborisov** [comment]
You're welcome!
