### ISSUE TITLE
NULL pointer dereference?

### ISSUE THREAD

**Issue by f2404** [lexborisov/myhtml#36]
clang-analyzer is concerned about the following code (https://github.com/lexborisov/myhtml/blob/master/source/myhtml/thread.c#L860) - it's thinking `qnode` may be NULL.
Can it really be in case if `queue->nodes_length >= queue->nodes_size`?
```c
    if(queue->nodes_length >= queue->nodes_size) {
        queue->nodes_uses++;
        
        mythread_queue_list_entry_wait_for_done(mythread, entry);
        mythread_queue_list_entry_clean(mythread, entry);
    }
    else
        queue->nodes_uses++;
    
    mythread_queue_node_t *qnode = &queue->nodes[queue->nodes_pos][queue->nodes_length];
    
    qnode->text  = text;
    qnode->begin = begin;
```

**Comment by lexborisov** [comment]
Hi!
No, NULL can't come. There are checks before using this code, but I think test for NULL value will not be excessive.

**Comment by lexborisov** [comment]
In code everything is right. In this case, all checks will be meaningless.
For a large HTML files this condition (queue->nodes_length >= queue->nodes_size) is triggered.

**Comment by f2404** [comment]
Hi @lexborisov 
So are you saying that everything is fine here, and no new checks are required? The issue may be closed in such case. Thanks.

**Comment by lexborisov** [comment]
Yes, everything is good here. Thank you for your attention to detail!
