### ISSUE TITLE
Serialize node

### ISSUE THREAD

**Issue by pedro93** [lexborisov/myhtml#38]
Given an html node, is there an api call to serialize it to a textual representation? A node.toString() if you will.

Thanks :)

**Comment by lexborisov** [comment]
Hi!
There are functions:

For [single node](https://github.com/lexborisov/myhtml/blob/master/include/myhtml/api.h#L869):
```C
myhtml_tree_print_node(tree, node, stdout); // stdout or your FILE*
```
For node and [node children](https://github.com/lexborisov/myhtml/blob/master/include/myhtml/api.h#L857):
```C
myhtml_tree_print_node_childs(tree,node, stdout, 0); // stdout or your FILE*
```

This is it?

**Comment by pedro93** [comment]
Yes, thank you very much :)

**Comment by lexborisov** [comment]
You are welcome!
