### ISSUE TITLE
Basic project skeleton using lib

### ISSUE THREAD

**Issue by pedro93** [lexborisov/myhtml#39]
Hi!

I apologize if this request sounds wierd but would it be possible to add an example c++ project template with a makefile ready to use this lib?
I am asking because, I am trying to create my project using this library but I must be having issues with my project structure and makefile as it can not link the necessary myhtml header files.

**Comment by f2404** [comment]
Have you looked into the examples directory? Isn't it helpful enough?

**Comment by pedro93** [comment]
I have, my problem with them are that they imply that the lib is installed into the machine  
```
cp lib/* /usr/local/lib
cp -r include/* /usr/local/include
```
I was looking for a more portable way, where I can have everything locally in the same folder. The reason behind it is because I later want to add bindings to other languages and for that I can't assume that the library and header files are pre-installed in target machines

**Comment by f2404** [comment]
> they imply that the lib is installed into the machine 

No, they don't.
The Makefile contains the paths to the lib and the headers which are not installed system-wide:
`
LIBS := ../lib/static_libmyhtml.a
LDLIBS := $(LIBS

CFLAGS += $(MyHTML_OPTIMIZATION_LEVEL) -fPIC --std=c99 -I../include
`
You can put the paths whatever you like, e.g. to the same directory where your sources are located.

**Comment by lexborisov** [comment]
or use cmake for [build and install](https://github.com/lexborisov/myhtml#build-and-installation) libraries and headers.

**Comment by pedro93** [comment]
Through trial and error I have found a way to do what I wanted. If I am able to complete my project with what I have, I can make a guide if you wish

**Comment by lexborisov** [comment]
It would be interesting to see what is the problem and how it was solved

**Comment by pedro93** [comment]
It is a very bad solution but what I have at the moment is the following project structure:
/
--lib/
------libmyhtml.dylib
------static_libmyhtml.a
--Makefile
--source/
------include/
------------//my header files
------------//myhtml header folder
------ //my source files

The Makefile has the following code:
```
SRCDIR := source

#Compiler flags
CFLAGS := -Wall -Werror -O2

CC ?= g++

SRCS := $(wildcard $(SRCDIR)/*.cpp) $(wildcard $(SRCDIR)/*.c)
HDRS := $(wildcard $(SRCDIR)/include/*.h)
LIB := $(wildcard lib/static_libmyhtml.a)
#Executable
PROG=domdiff

all:
	$(CC) $(CFLAGS) $(SRCS) $(LIB) -o $(PROG)

clean:
	rm -f $(PROG)
```

All references to the header files are made like this:
```cpp
#include "include/..."
```

Not exactly what I intended but for now it works

**Comment by f2404** [comment]
You can add an '-I<path>' parameter as shown above to get rid of "include/" prefixes for the headers.

**Comment by pedro93** [comment]
I had tried but it did not work for me for some reason, I haven't had time to look into it very much:

```
SRCDIR := source

CC ?= g++

SRCS := $(wildcard $(SRCDIR)/*.cpp) $(wildcard $(SRCDIR)/*.c)
HDRS := $(wildcard $(SRCDIR)/include/*.h)
LIB := $(wildcard lib/static_libmyhtml.a)

#Executable
PROG=domdiff

#Compiler flags
CFLAGS := -Wall -Werror -O2 -I $(HRDS)

all:
    $(CC) $(CFLAGS) $(SRCS) $(LIB) -o $(PROG)

clean:
    rm -f $(PROG)
```

**Comment by f2404** [comment]
No, you should pass the directory name, not the files.

**Comment by lexborisov** [comment]
something like
```sh
HDRS := -I$(SRCDIR)/include -I$(SRCDIR)/include/my header files
```

**Comment by pedro93** [comment]
It is now working, thank you very much for your help @lexborisov @f2404  👍

**Comment by lexborisov** [comment]
You are welcome!
See [gnu make manual](http://www.gnu.org/software/make/manual/make.html)
