### ISSUE TITLE
Use of angle brackets around file names for include statements

### ISSUE THREAD

**Issue by elfring** [lexborisov/myhtml#41]
Would you like to [replace any double quotes](https://github.com/lexborisov/myhtml/blob/48cb16e3651239577f85be31ad694e6e3b8e8340/include/myhtml/tag.h#L29 "Check header file inclusion style.") by [angle brackets around file names for include statements](http://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename "What is the difference between #include <filename> and #include “filename”?")?

**Comment by lexborisov** [comment]
But why? By spec [C99](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1256.pdf)

> A preprocessing directive of the form
> **#include "q-char-sequence" new-line**
> causes the replacement of that directive by the entire contents of the source file identified
> by the specified sequence between the " delimiters. The named source file is searched
> for in an implementation-defined manner. If this search is not supported, or if the search
> fails, the directive is reprocessed as if it read
> **#include \<h-char-sequence\> new-line**
> with the identical contained sequence (including \> characters, if any) from the original
> directive.

It seems logical.

**Comment by elnormous** [comment]
@lexborisov, please see this discussion: https://github.com/elnormous/ouzel/issues/4

**Comment by lexborisov** [comment]
Now the public headers (they are installing with a library) used by angle brackets. Is embedded project him still remain double quotes

**Comment by lexborisov** [comment]
I think that this issue has been resolved. Thanks!

**Comment by elfring** [comment]
Thanks for [your source code improvement](https://github.com/lexborisov/myhtml/commit/d27eb55d8ac4bd0ea02742182af3edef4ea7ad65 "Changed include method for public headers.").

**Comment by lexborisov** [comment]
You're welcome!
