### ISSUE TITLE
any recent change in function myhtml_node_remove?

### ISSUE THREAD

**Issue by kostya** [lexborisov/myhtml#45]
i get segfault on line: https://github.com/kostya/myhtml/blob/master/spec/node_spec.cr#L166, on function remove!
not found why it happens

https://github.com/kostya/myhtml/blob/master/src/myhtml/lib.cr#L36

**Comment by lexborisov** [comment]
`myhtml_tree_node_remove` has been changed. 

Now you need to pass two arguments: myhtml_tree_t* and myhtml_tree_node_t*
Previously, only one argument was necessary to pass: myhtml_tree_node_t*

```C
myhtml_tree_node_remove(myhtml_tree_t* tree, myhtml_tree_node_t* node)
```

**Comment by kostya** [comment]
thanks

**Comment by lexborisov** [comment]
You're welcome!
