### ISSUE TITLE
Null pointer dereference in html2sexpr

### ISSUE THREAD

**Issue by pascal-cuoq** [lexborisov/myhtml#48]
In the utility `html2sexpr`, a null pointer can be passed to `printf("%s…` for some input files.

To reproduce, instrument the code as shown:
```
--- examples/html2sexpr.c~	2016-07-13 12:48:12.000000000 +0200
+++ examples/html2sexpr.c	2016-07-13 23:28:59.926936062 +0200
@@ -57,7 +57,11 @@
     myhtml_tree_attr_t* attr = myhtml_node_attribute_first(root);
     while (attr != NULL) {
         /* attribute sexpr (name value)*/
-        printf("(%s \'%s\')", myhtml_attribute_key(attr, NULL), myhtml_attribute_value(attr, NULL));
+        const char *value = myhtml_attribute_value(attr, NULL);
+        if (!value)
+          fprintf(stderr,"Pointer is null, should not be printed!!!\n");
+        else
+          printf("(%s \'%s\')", myhtml_attribute_key(attr, NULL), value);
         attr = myhtml_attribute_next(attr);
     }
 
```

Build and run `examples/html2sexpr 1.txt` (the name [1.txt](https://github.com/lexborisov/myhtml/files/362498/1.txt) being chosen because of GitHub limitations on file uploads). The log should show the message “Pointer is null, should not be printed!!!” several times.

This indicates that a null pointer is being passed to `printf("%s…`. This is not a legal value for the `%s` format, even if Glibc accepts it. For `%s` the C standard says [“the argument shall be a pointer to the initial element of an array of character type”](http://port70.net/~nsz/c/c11/n1570.html#7.21.6.1p8).

**Comment by lexborisov** [comment]
Thanks!
The value can be NULL. For example: <input disabled> key: disabled; value: NULL;
It is not necessary to write in strerr.
