### ISSUE TITLE
For some inputs, key can be NULL

### ISSUE THREAD

**Issue by pascal-cuoq** [lexborisov/myhtml#50]
When the attached input [nullkey.txt](https://github.com/lexborisov/myhtml/files/363725/nullkey.txt) is passed to the command `html2sexpr`, the key ends up being a null pointer too.

I have instrumented the code as follows in order to show it:
```
diff --git a/examples/html2sexpr.c b/examples/html2sexpr.c
index 9e6558e..28f0baa 100644
--- a/examples/html2sexpr.c
+++ b/examples/html2sexpr.c
@@ -57,12 +57,15 @@ static void walk_subtree(myhtml_tree_t* tree, myhtml_tree_node_t* root, int leve
     myhtml_tree_attr_t* attr = myhtml_node_attribute_first(root);
     while (attr != NULL) {
         /* attribute sexpr (name value)*/
+        const char *key = myhtml_attribute_key(attr, NULL);
         const char *value = myhtml_attribute_value(attr, NULL);
-        
+
+        if (key == NULL)
+            printf("(KEY IS NULL)");
         else if (value)
-            printf("(%s \'%s\')", myhtml_attribute_key(attr, NULL), value);
+            printf("(%s \'%s\')", key, value);
         else
-            printf("(%s)", myhtml_attribute_key(attr, NULL));
+            printf("(%s)", key);
         
         attr = myhtml_attribute_next(attr);
     }
```

When I pass the provided file, the result is:

```
~/myhtml$ ./html2sexpr nullkey.txt  | grep "KEY IS NULL"
        <element name=')(a")…(element(name 'e')(empty(KEY IS NULL)
```

This is related to https://github.com/lexborisov/myhtml/issues/48 : it is in the same location, but again I don't know if the fix should be to treat the situation as normal or to prevent it from happening. Please never mind that the input nullkey.txt looks nothing like HTML: I used an existing test suite for XML parsers. An HTML parser should not invoke undefined behavior for any input, valid HTML or not.

**Comment by lexborisov** [comment]
Thanks!

You find interesting bug. Fixed. Null key can only be a DOCTYPE, for everything else, it should not be.
