### ISSUE TITLE
NULL pointer dereference when calloc() fails in MyHTML_BUILD_WITHOUT_THREADS mode

### ISSUE THREAD

**Issue by pascal-cuoq** [lexborisov/myhtml#51]
This report is specific to the `MyHTML_BUILD_WITHOUT_THREADS` mode. The [tool](http://trust-in-soft.com/tis-interpreter/) I'm using does not support threads, so I have to limit my exploration of myhtml to this mode.

Consider the lines [64 through 106 in myhtml.c](https://github.com/lexborisov/myhtml/blob/b8fadce1a6e4df06375411a94252ea7c1f4f31e1/source/myhtml/myhtml.c#L64-L106):

```
    myhtml->thread = mythread_create();
    
    status = mythread_init(myhtml->thread, NULL, thread_count, queue_size);
    
    if(status)
        return status;

    …
    
    myhtml_clean(myhtml);
```

The function `mythread_create` [directly returns](https://github.com/lexborisov/myhtml/blob/3850d4291f7a83f5e6270882747f6e2546b009c5/source/myhtml/thread.c#L256-L263) the result of `calloc`. This can be a null pointer if this allocation fails.

Then, the function `mythread_init`, in the `MyHTML_BUILD_WITHOUT_THREADS` mode, always returns `MyHTML_STATUS_OK`, which is `0`.

Then the call `myhtml_clean(myhtml)` calls `mythread_clean(myhtml->thread)`. The function `mythread_clean` dereferences its argument `mythread` (it does `mythread->sys_last_error = 0;`). In the scenario above, `mythread` is a null pointer.

**Comment by lexborisov** [comment]
Thanks!
