### ISSUE TITLE
Low API don't contain MYHTML_FAILED

### ISSUE THREAD

**Issue by horpto** [lexborisov/myhtml#53]
По идее же low API содержит то что и high, но предоставляет дополнительные возможности?

**Comment by lexborisov** [comment]
Привет
Разница лишь в том, что "низкое" api не дает возможности смотреть в структуры. То есть, нужно пользоваться только функциями. Вот пример, вернуть html ноду:
low: tree->node_html
high: myhtml_tree_get_node_html(tree)

Я могу гарантировать, что high api не изменится, как минимум кардинально не изменится.
С low api всё иначе. Конечно, менять его постоянно я не собираюсь, но так же не могу дать гарантию что структуры не будут меняться.

Вообще, сам я использую повсеместно low api. И в случаи изменения внесения изменений отражаю их в changelog

Если ответить прямо на вопрос то да, с low api больше гибкости и возможностей.

Про MYHTML_FAILED — это кто-то реализовал, а я не заметил как оно попало в публичное апи. Я бы его вообще удалил или переименовал в MyHTML_FAILED.

**Comment by horpto** [comment]
Я использую low API из-за myhtml_string, не хотел создавать велосипед для прохода и суммирования по тексту, но в остальном я предпочитаю всё таки не обращаться напрямую к структурам. 

MYHTML_FAILED используется только в примерах. Не знаю, можно ли ещё безопасно удалить или переименовать его, но у себя я его не юзаю.

**Comment by lexborisov** [comment]
Вы можете дополнить публичное апи (high api) тем что не хватает вам и прислать реквест или объяснить что именно недоступно в публичном апи из myhtml_string.

MYHTML_FAILED кто-то может пользоваться, резко лучше не удалять. Лучше объявлю как устаревшую и создам рядом MyHTML_FAILED. Так будет более правильно.

**Comment by lexborisov** [comment]
Добавил MyHTML_FAILED в оба апи.

**Comment by horpto** [comment]
Спасибо
