### ISSUE TITLE
HTML title node doesn't contain inner text

### ISSUE THREAD

**Issue by horpto** [lexborisov/myhtml#54]

**Comment by lexborisov** [comment]
Hi!

I need an example. Always contain if text exists.

**Comment by horpto** [comment]
А, это из-за флага `MyHTML_TREE_PARSE_FLAGS_SKIP_WHITESPACE_TOKEN`

пример достаточно такой:
```
<!DOCTYPE html> <html><head><meta http-equiv='content-type' content='text/html; charset=utf-8' />  <title> ваываыва</title> </head><body>    <p>dsfsd</p></body></html>
```

**Comment by lexborisov** [comment]
Спасибо! Сегодня, к сожалению, я не имеют доступ к компьютеру, завтра разберусь с этим моментом.

**Comment by lexborisov** [comment]
Исправил.
Изменились правила для пропуска/выкидывания пустых токенов. Для токенов типа: RCDATA, RAWTEXT, CDATA and PLAINTEXT пустые токены пропускаться не будут.

Спасибо, что заметили это!
