### ISSUE TITLE
external allocator and free

### ISSUE THREAD

**Issue by kostya** [lexborisov/myhtml#55]
would be nice to have callbacks to call external allocation and free functions for language with GC(like pcre for example: https://github.com/crystal-lang/crystal/blob/5bcf6d51dfffec4f8acc62e6e7af7e029e55de37/src/regex/lib_pcre.cr#L26)

**Comment by lexborisov** [comment]
Hi!

Ok, I will try to do something!

**Comment by lexborisov** [comment]
Done! See [how add new port](https://github.com/lexborisov/Modest/wiki/Add-new-port)
