### ISSUE TITLE
question about body

### ISSUE THREAD

**Issue by kostya** [lexborisov/myhtml#56]
myhtml always parse body as full content between `</head>` and `</html>`

but there is many edge cases:

self-closed body:
```html
<html>
<head></head>
<body/>
  <a href="..."> </a>
</body>
</html>
```

not-closed body:
```html
<html>
<head></head>
<a href="..."> </a>
<body>
</html>

```

tag outside body:
```html
<html>
<head></head>
<a href="..."> </a>
<body>
</body>
</html>

```

multiple bodies:
```html
<html>
<head></head>
<body>
</body>

...
<body>
<a href="..."> </a>
</body>

</html>

```

is there any way to check that tag `a` inside body or not?
libxml allow to check this

**Comment by lexborisov** [comment]
Hi!

I did not understand your question. XML is not HTML parser. In HTML self-closing flag not using in parsing, with the exception of tag [math and svg](https://html.spec.whatwg.org/multipage/syntax.html#parsing-main-inbody:self-closing-flag) and [The rules for parsing tokens in foreign content](https://html.spec.whatwg.org/multipage/syntax.html#parsing-main-inforeign:self-closing-flag). 

At the moment, the parser (MyHTML) works as well as modern browsers, in other words, it conforms to [the specification](https://html.spec.whatwg.org).

For get any tag in scope use:
```C
myhtml_collection_t *collection = myhtml_get_nodes_by_tag_id_in_scope(tree, NULL, myhtml_tree_get_node_body(tree), MyHTML_TAG_A, NULL);
```

or use [CSS Selectors in Modest project](https://github.com/lexborisov/Modest/blob/master/examples/selectors/selectors_low_level.c)

libxml It is not a valid html parser.

**Comment by kostya** [comment]
вопрос в том что в реальных страницах иногда встречаются случаи выше, будут ли все браузеры отображать эту ссылку или нет? и во всех случаях myhtml поместит ссылку в тег <body>?

**Comment by lexborisov** [comment]
Браузеры должны её отображать. Во всех случаях ссылка будет помещена в тело, смотри правила [The "after body" insertion mode](https://html.spec.whatwg.org/multipage/syntax.html#parsing-main-afterbody)

После закрытия тела (body) если приходят теги не html, doctype, comment или текстовый то режим обработки переключается в [The "in body" insertion mode](https://html.spec.whatwg.org/multipage/syntax.html#parsing-main-inbody)
