### ISSUE TITLE
myhtml replaced invalid entities

### ISSUE THREAD

**Issue by kostya** [lexborisov/myhtml#57]
```html
<div>aaa &gt bbb</div>
```

```
./print_tree_high_level /tmp/1.html
<html>
       	<head>
       	<body>
       		<div>
       			<-text>: aaa > bbb
       		<-text>:
```
entity should end with `;`

**Comment by lexborisov** [comment]
No! You are not right. See [named-character-references](https://html.spec.whatwg.org/multipage/syntax.html#named-character-references)

&GT;, &GT, &gt; and &gt == '>'

**Comment by kostya** [comment]
hm, if named allowed without `;`, what about &#61 without `;`, also?

**Comment by lexborisov** [comment]
I do not teach HTML. See HTML specification [Character reference state](https://html.spec.whatwg.org/multipage/syntax.html#character-reference-state) or tested in modern browsers.

**Comment by kostya** [comment]
ок, спасибо, довольно сложно найти вообще баги в myhtml, все работает
перевожу один проект с libxml, вот он не заменял, упали тесты, думал тут тоже баг, оказалось ожидаемое поведение

**Comment by lexborisov** [comment]
Не за что, обращайся. Но, пожалуйста, на будущее, большенство вопросов можно решить проверкой в современном браузере. Это отнимает время от работы над проектом, а времени у меня всё меньше :)

**Comment by kostya** [comment]
Можно добавить в апи две функции на конвертацию entities туда и обратно для входной строки? Если не сложно?

**Comment by lexborisov** [comment]
Для myhtml_string можно, манипуляций не потребуется. А вот если для char* выделенным сторонним malloc нужно будет переписывать.
