### ISSUE TITLE
myhtml_token_node_text always return null

### ISSUE THREAD

**Issue by kostya** [lexborisov/myhtml#59]
callback function for myhtml_callback_before_token_done_set:
```c
void * colorize_callback_before_token_done(myhtml_tree_t* tree, myhtml_token_node_t* token, void* ctx)
{
    size_t length;
    const char *text = myhtml_token_node_text(token, &length);

    printf("%d %s\n", length, text);
    
    return ctx;
}
```

for
```html
<a href='/link1'>Link1</a>
<div>bla</div>
```

prints:
```
0 (null)
0 (null)
0 (null)
0 (null)
0 (null)
0 (null)
0 (null)
0 (null)
0 (null)

```

**Comment by horpto** [comment]
а флаги установлены?

**Comment by kostya** [comment]
нет без флагов вообще

**Comment by horpto** [comment]
А, это не баг, а фича,  используй 'after', а не 'before'.
Если смотреть код, то там при процессинге токена обрабатываются и добавляются данные в `token.str` (данные из этого поля и отдает `myhtml_token_node_text`, если конкретно, то поле `token.str.data`)

код содержит почти все ответы.

**Comment by kostya** [comment]
спс
