### ISSUE TITLE
autoreplace tag noindex

### ISSUE THREAD

**Issue by kostya** [lexborisov/myhtml#64]
noindex is not a tree tag, it is actually invalid. (it should not be autoclosed by some tags).

what if myhtml autoreplace this tags to it valid version, when parsing?
`<noindex>` with `<!--noindex-->`
`</noindex>` with `<!--/noindex-->`
https://yandex.ru/support/webmaster/controlling-robot/html.xml?lang=en#noindex

so it still be in tree, we can find it start and end, by finding `_comment` nodes, and comparing its content

**Comment by kostya** [comment]
also i can do this replace by regexp before parsing, but it should be much slower.

**Comment by lexborisov** [comment]
Hi! I did not understand your question. Why would I do that? MyHTML parser conforms to the specification, and is not there any rules for the tag noindex. See "Any other start tag" in [parsing-main-inbody](https://html.spec.whatwg.org/multipage/syntax.html#parsing-main-inbody)
