### ISSUE TITLE
Binding for Python!

### ISSUE THREAD

**Issue by lexborisov** [lexborisov/myhtml#65]
Need help for creating binding for Python!

**Comment by horpto** [comment]
hm, maybe [swig](http://www.swig.org/tutorial.html)?

**Comment by lexborisov** [comment]
Thanks! But, I want something to do with OOP. Not clear how it should be.

**Comment by keithstellyes** [comment]
Is this still being worked on? I would love to help out

**Comment by lexborisov** [comment]
Hi @keithstellyes 
Many people would be very grateful if you help with this!

**Comment by keithstellyes** [comment]
Just an update, I've been working on this, going to try using Cython. It's a bit tedious trying to get bindings down so I might spend the next month or three getting more comfortable with Cython.

It'd be easier if documentation was more extensive. Maybe we could try to work on that?

**Comment by lexborisov** [comment]
In current time I create rendering in [Modest](https://github.com/lexborisov/Modest) project (myhtml is one of module of the Modest)
Unfortunately, I do not have time to write full documentation, but I am ready to answer any questions on any functions in any time.
There is a small description of the functions in the [file](https://github.com/lexborisov/myhtml/blob/master/include/myhtml/api.h#L581)

In any case, I am ready to assist in every possible way in creating the binding for myhtml.

You can join to [#modest-engine on irc.freenode.net](http://webchat.freenode.net/?channels=%23modest-engine) (my nick lexbor) or send any questions to my email: lex.borisov at gmail.com

**Comment by lexborisov** [comment]
There is already a solution: [selectolax](https://github.com/rushter/selectolax)
