### ISSUE TITLE
Retrieving modified HTML

### ISSUE THREAD

**Issue by martijnotto** [lexborisov/myhtml#66]
Perhaps I'm being very silly but I cannot find a way to retrieve the modified HTML from the tree. If I print the tree by using myhtml_tree_print_node_children I can see all the modifications, but this output is of course not the HTML I want.

The only way I found to get HTML out again was using myhtml_tree_incoming_buffer_first, but this gets me the unmodified HTML, which is not useful to me.

What is the correct way of doing this?

**Comment by lexborisov** [comment]
Hi! 
You want to make a serialization of the the final tree? See [example](https://github.com/lexborisov/myhtml/blob/master/examples/print_tree_high_level.c).

Or I can create [serialization](https://html.spec.whatwg.org/multipage/syntax.html#serialising-html-fragments) as required by the specification. Something like a function that will return const char * of fully modified HTML.

**Comment by martijnotto** [comment]
I would - of course - be very happy if you were to make a full serialization algorithm. It would save a lot of work for me traversing the whole tree to build all the attributes.

**Comment by lexborisov** [comment]
Ok, I will create it

**Comment by lexborisov** [comment]
Done. See [example](https://github.com/lexborisov/myhtml/blob/master/examples/serialization_high_level.c). But, I have not time to test this. Please, test the serialization function.

**Comment by martijnotto** [comment]
It seems to work well when serializing HTML that is already valid. When you parse something invalid and then serialize it the library fixes this to make the output valid (which is good!), but not all the elements that appear in the output can be found using myhtml_get_nodes_by_tag_id.

Observe the following - obviously incorrect - HTML code:

    <!DOCTYPE html>
    <html>
        <body>
            <code><a href="http://www.google.com/?q=google"></code>Google it!<code></a></code>
        </body>
    </html>

This gets serialized to the following output:

    <!DOCTYPE html><html><head></head><body>
            <code><a href="http://www.google.com/?q=google"></a></code><a href="http://www.google.com/?q=google">Google it!<code></code></a>
        
    
    </body></html>

As you can see the invalid code tag has caused the the <a> tag to be sort of duplicated. Only the first of these tags is findable using myhtml_get_nodes_by_tag_id.

**Comment by lexborisov** [comment]
Fixed! 
Thanks!
