### ISSUE TITLE
Nice serialization features to have

### ISSUE THREAD

**Issue by EmielBruijntjes** [lexborisov/myhtml#68]
Extremely cool library. Thanks for all the great work. A couple of serialization features that would be very nice to have are:

**A custom output function instead of outputting everything to a dynamically allocated string**
When we want to write the serialized HTML document to a file, or a network connection, or assign to some other kind of variable (like a std::string), it is now a bit of overhead that the myhtml_serialize*() function first allocates a string that we then have to copy. It would be better to (have the option) to pass a callback instead:

````
void my_output_function(const char *data, size_t size, void *ptr)
{
    // own implementation
}

myhtml_serialize(tree, node, my_output_function, nullptr);
````

**An option to serialize only the changes / maintain the original input**
When we call myhtml_serialize(), we get a completely new, normalized and repaired HTML document. That's cool. However, we want to keep the generated HTML code as close to the original input as possible - even if the original input contained errors. We use the library to make small changes to HTML code (we change a couple of hyperlinks), and we want to preserve all other original code. 

Maybe it's possible to add an extra "flags" parameter to the myhtml_serialize() method to choose the type of serialization to use: one that completely regenerates the document (the current behavior), or one that outputs the original input, and only serializes the modified nodes.

**Comment by lexborisov** [comment]
Hi! Thanks!

> A custom output function instead of outputting everything to a dynamically allocated string

In order not to break the current functionality:
```C
void my_output_function(myhtml_tree_node_t* node, const char *data, size_t size, void *ptr)
{
    // "myhtml_tree_node_t* node" current serialization node
    // "const char* data" is it temp buffer, it is overwritten
}

myhtml_serialization_with_callback(tree, node, my_output_function, nullptr);
```

I will do this in the near future.

> An option to serialize only the changes / maintain the original input

Is it possible. We'll have to build a reverse index position for changed tokens. Sorry, but I do not have time to deal with this.
