### ISSUE TITLE
Поправить язык в README.md + добавить баннеров с travis-ci

### ISSUE THREAD

**Issue by warfish** [lexborisov/myhtml#7]
- Поправить язык
- Добавить описание сборки под линуксом
- Добавить билд статус баннер с тревиса

**Comment by lexborisov** [comment]
1) Английский? — На тебя вся надежда)
2) Обычный make не собирает?
3) Он там не собирается под gcc 4.6.3
Нахрапом использовал спин локи которые появились в 4.7, глянь mcasync.
Заход в эти локи крайне редкий и маловероятный. Сейчас пытаюсь понять какой #ifdef поставить чтобы определить присутствуют ли спин локи или нет. Если их нет, то надо использовать стандартные мютексы.
