### ISSUE TITLE
Find elements by attribute

### ISSUE THREAD

**Issue by lucaswxp** [lexborisov/myhtml#71]
How would I go about trying to query all elements that have a given attribute value?

Is there any example on this?

**Comment by lexborisov** [comment]
Hi!
Of course there is, try [example](https://github.com/lexborisov/myhtml/blob/master/examples/nodes_by_attr_value_high_level.c) and see [Public API](https://github.com/lexborisov/myhtml/blob/master/include/myhtml/api.h#L1076)

**Comment by lucaswxp** [comment]
Thanks!

But I can't compile, I get error: http://pastebin.com/irrXaXWm
Command: g++ test.cpp 

This is my first c++ program, I probably did something wrong. Can you help me?

**Comment by lexborisov** [comment]
Some:
```bash
g++ test.cpp -L/path/to/lib -lmyhtml -I/path/to/headers/myhtml
```

See [gcc linker options -l](https://gcc.gnu.org/onlinedocs/gcc/Link-Options.html) and [-L and -I options](https://gcc.gnu.org/onlinedocs/gcc/Directory-Options.html)
See [Shared libraries with GCC](http://www.cprogramming.com/tutorial/shared-libraries-linux-gcc.html)

or build all source files in source/myhtml to your program.

Read the resources, I do not teach programming.

**Comment by lucaswxp** [comment]
@lexborisov Sorry! I missed that part in the docs, was following another compiling tutorial. Thanks again!

**Comment by lexborisov** [comment]
You're welcome!
