### ISSUE TITLE
Help getting inner text of a node

### ISSUE THREAD

**Issue by lucaswxp** [lexborisov/myhtml#72]
Hi again!

So this is what I came up with:

``` cpp

string myhtml_node_inner_text(myhtml_tree_node_t* node, bool include_script_tags = false, bool include_style_tags = false){
  string text_buffer = "";

  myhtml_tree_node_t* current = myhtml_node_child(node);

  if(current){
    do {
      myhtml_tag_id_t current_id = myhtml_node_tag_id(current);

      if(!include_script_tags && current_id == MyHTML_TAG_SCRIPT){
        continue;
      }
      if(!include_style_tags && current_id == MyHTML_TAG_STYLE){
        continue;
      }

      if(myhtml_node_is_close_self(current)){
        continue;
      }

      if(current_id == MyHTML_TAG__TEXT){
        text_buffer += myhtml_node_text(current, NULL);
      }else{
        text_buffer += myhtml_node_inner_text(current);
      }
    } while((current = myhtml_node_next(current)));
  }

  return text_buffer;
}}
```

It seems to work ok, but I would like to implement it following the project patterns, not sure how to use myhtml_string_t, if acceptable, I'll do a pull request.

**Comment by lexborisov** [comment]
Hi!

MyHTML project implemented as a pure C not C++. C != C++. But, library written in C can be used in C++. In C there is no string object. All libraries in Linux have a C API (or almost all). This allows the use of a library in different programming languages 
such as С++.

See [How to mix C and C++](https://isocpp.org/wiki/faq/mixing-c-and-cpp) and [Mixing C and C++ Code in the Same Program](http://www.oracle.com/technetwork/articles/servers-storage-dev/mixingcandcpluspluscode-305840.html)

And see [this example](https://github.com/lexborisov/myhtml/blob/master/examples/serialization_high_level.c) and [serialization API](https://github.com/lexborisov/myhtml/blob/master/include/myhtml/api.h#L2710)
