### ISSUE TITLE
xpath

### ISSUE THREAD

**Issue by kostya** [lexborisov/myhtml#73]
hi, is there any plans to implement xpath?

**Comment by lexborisov** [comment]
Hi!
by [spec](https://www.w3.org/TR/xpath-full-text-30/)? It is in the lowest priority.

**Comment by Vitaliy-Grigoriev** [comment]
In the vastness of Git there is such a HTML parser project by Google: [link](https://github.com/google/gumbo-parser)
This project has a very useful extension for searching the tree node and attributes that supports JQuery standard: [link](https://github.com/lazytiger/gumbo-query)

**Comment by lexborisov** [comment]
Oh, use [Modest](https://github.com/lexborisov/Modest) to make full use CSS Selectors. See [example](https://github.com/lexborisov/Modest/blob/master/examples/selectors/selectors_low_level.c)

Gumbo slow and does not correspond to the actual specification.

**Comment by dbeacham** [comment]
If I'm going to be writing bindings to take use of the css selectors should I write separate bindings against myhtml, mycss and use those when writing the modest bindings or are the versions of myhtml, mycss in the modest repository kept up to date?

**Comment by lexborisov** [comment]
Hi @dbeacham !
All code developed in Modest, then simply copied into myhtml, mycss (
i.e., always kept up to date).

I would be really happy to have a binding for another programming language. You can ask any questions to the [mail](mailto:lex.borisov@gmail.com). 

Thank you!

**Comment by kostya** [comment]
binding for crystal, it was quite easy to write because of nice api, thanks: https://github.com/kostya/modest

**Comment by lexborisov** [comment]
@kostya , Thanks, and thanks for binding!
