### ISSUE TITLE
Test on a set of compilers

### ISSUE THREAD

**Issue by Vitaliy-Grigoriev** [lexborisov/myhtml#74]
Hi!
Please, test your library on a set of compilers or different versions of **gcc**.
For example, I use **clang** for my projects and in this case you library compiling successfully.
But if I using **gcc** (v 6.1.1+), there is some _uncomfortable_ bugs, such as:

`parse_without_whitespace.c: In function ‘load_html_file’:
parse_without_whitespace.c:57:5: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
     if(size < 0)
     ^~
parse_without_whitespace.c:60:9: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
         struct res_html res = {html, (size_t)size};
         ^~~~~~
cc1: all warnings being treated as errors`

Thank you!

**Comment by lexborisov** [comment]
Hi!
Thanks!
parse_without_whitespace.c it is example. Now I try find gcc 6.1 to understand it out

**Comment by lexborisov** [comment]
Thanks! 
Fixed!
