### ISSUE TITLE
myhtml_tree_init выедает 3MB

### ISSUE THREAD

**Issue by Azq2** [lexborisov/myhtml#75]
Вот такой код:

```
myhtml_t* myhtml = myhtml_create();
myhtml_init(myhtml, MyHTML_OPTIONS_DEFAULT, 1, 0);
myhtml_tree_init(myhtml_tree_create(), myhtml);
```

Приводит вот к чему:

```
==8138==     in use at exit: 3,366,344 bytes in 91 blocks
```

Считаю, что это очень жирно, если нужно парсить очень мелкие фрагменты HTML. 
И это ограничивает использование на девайсах с маленьким объёмом RAM.

Было бы круто иметь возможность самому задать нужные значения начальных буфферов (и %/размер их увеличения при следующей реалокации)

**Comment by lexborisov** [comment]
Привет! 

Действительно, тут вы правы, начальные значения буферов были поставлены "с потолка" в первой версии парсера.

Да, конечно, логично сделать возможным указывать эти параметры. Плюсом к этому сделаю возможность компиляции без внутреннего менеджера памяти/объектов, то есть работу напрямую с malloc, realloc и free.

Постараюсь к середине/концу будущей недели запилить всё это.
Спасибо, что обратили внимание на это!

**Comment by lexborisov** [comment]
И если не сложно, посмотрите, пожалуйста, сколько он съест памяти в безтредовом режиме:
```C
myhtml_t* myhtml = myhtml_create();
myhtml_init(myhtml, MyHTML_OPTIONS_PARSE_MODE_SINGLE, 1, 0);
myhtml_tree_init(myhtml_tree_create(), myhtml);
```

**Comment by Azq2** [comment]
Чуть меньше.
```
==9151==     in use at exit: 3,295,824 bytes in 82 blocks
```

**Comment by lexborisov** [comment]
Спасибо! 
Поправлю это место.

**Comment by lexborisov** [comment]
Fixed in [commit](https://github.com/lexborisov/myhtml/commit/d3ea5cf59c4115dbe78a816ea915da86e49e9bea)!
Thanks!
