### ISSUE TITLE
double underscores in myhtml_tags enum

### ISSUE THREAD

**Issue by dbeacham** [lexborisov/myhtml#76]
Hi - can you quickly describe the difference between

`MyHTML_TAG__TEXT` and `MyHTML_TAG_TEXT`
`MyHTML_TAG__COMMENT` and `MyHTML_TAG_COMMENT`

? There are also a few other double underscored enum values

`MyHTML_TAG__UNDEF`
`MyHTML_TAG__DOCTYPE`
`MyHTML__END_OF_FILE`

If I can better understand the differences or what the double underscore represents it'll make writing my bindings and documentation a lot easier.

**Comment by lexborisov** [comment]
Hi!

In theory, the tags can be named undef, text and other. I.e
```HTML
<text blah="bluh">MyHTML_TAG_TEXT</text>
<comment blah="bluh">MyHTML_TAG_COMMENT</comment>
...
```
but the tag can not start with "_" or "-".

If these tags are ever add to the specification that there will be problems. Simply, it is the reserved tags:
```C
"tag name not set" = MyHTML_TAG__UNDEF
"any text" = MyHTML_TAG__TEXT
"<!--" = MyHTML_TAG__COMMENT
"<!DOCTYPE" = MyHTML_TAG__DOCTYPE
"System, need for currently stop parsing. For internal use only" = MyHTML_TAG__END_OF_FILE
```
This ensures that no further collisions occur.
