### ISSUE TITLE
How to query a returned myhtml_collection_t?

### ISSUE THREAD

**Issue by lucaswxp** [lexborisov/myhtml#78]
I need to query the equivalent of CSS selector `#myid .classname`

This is what I tried:
```
  myhtml_collection_t* billet = myhtml_get_nodes_by_attribute_value(tree, NULL, NULL, false, "id", strlen("id"), "myid", strlen("myid"), NULL);
  myhtml_collection_t* billetChild = myhtml_get_nodes_by_attribute_value_whitespace_separated(tree, billet, NULL, false, "class", strlen("class"), "classname", strlen("classname"), NULL);

  if(billet->length > 0){
    myhtml_node_text(myhtml_node_child(billetChild->list[0]), NULL); // (null)
  }
```

I tried to look at api.h for enlightenment, but no luck =/

**Comment by lexborisov** [comment]
Hi, @lucaswxp 

It is not work so. 
Try this:
```C
myhtml_collection_t* billet = myhtml_get_nodes_by_attribute_value(tree, NULL, NULL, false, "id", strlen("id"), "myid", strlen("myid"), NULL);
myhtml_collection_t* billetChild = NULL;

for(size_t i = 0; i < billet->length; i++) {
/* billet->list[i] -- scope node */
   billetChild = myhtml_get_nodes_by_attribute_value_whitespace_separated(tree, billetChild, billet->list[i], false, "class", strlen("class"), "classname", strlen("classname"), NULL);
}

for(size_t i = 0; i < billetChild->length; i++) {
    // and see
    // myhtml_serialization_tree_callback
    // or myhtml_serialization_tree_buffer
    // or do self
}
```

Do you want to try the full css selectors in Modest? See [example](https://github.com/lexborisov/Modest/blob/master/examples/selectors/selectors_find_nodes_low_level.c). Is simple to use and it is very effective (fast and so on).

**Comment by lucaswxp** [comment]
@lexborisov Thanks! That makes sense.

Also, nice to know about Modest, but I'm migrating some nodejs code from cheerio library, because cheerio is too slow for the job. You probably won't know this without benchmarking, but do you think if Modest should be much faster than cheerio?

**Comment by lexborisov** [comment]
Now I have no benchmark, but I think it will be faster than cheerio. Modest contains fast CSS parser (really fast) and support once preparing selectors query and use him many time for any html tree.

For example, average search time by selector, in tree of 5000 nodes, takes 0.0001-0.0002 sec (0.1-0.2ms), some like "#id :not([ref])".

In the near future I'll create benchmarks.

**Comment by lucaswxp** [comment]
Thanks! That's very helpful.

**Comment by kostya** [comment]
i have a simple benchmark compared with libxml: https://github.com/kostya/modest#benchmark
