### ISSUE TITLE
unable to make library compile error

### ISSUE THREAD

**Issue by MuhammadAasharib** [lexborisov/myhtml#79]
![Uploading Capture67.PNG…]()
there are error on compile time and i am unable to generate library from source code

**Comment by lexborisov** [comment]
Hi!
Can you give an example? OS? Compiler?

**Comment by MuhammadAasharib** [comment]
Hello,
Windows 8.1 and gcc compiler. I have also tried visual studio 2015 but no results.
![capture67](https://cloud.githubusercontent.com/assets/18683160/21439223/8c093ce2-c8ae-11e6-8841-3ec51aa9819c.PNG)

**Comment by lexborisov** [comment]
You have solved the problem?

**Comment by MuhammadAasharib** [comment]
No the problem isn't solved yet
![capture67](https://cloud.githubusercontent.com/assets/18683160/21439317/28fd6e1a-c8af-11e6-9b58-4b78ddf18889.PNG)

**Comment by lexborisov** [comment]
Describe all the software you are using: name, version.
In fact, it can be removed ```#pragma once```.
But, it is not clear why your compiler considers his obsolete.

**Comment by MuhammadAasharib** [comment]
CYGWINB20, GCC COMPILER FOR WINDOWS
