### ISSUE TITLE
Unable Include this Library in Visual Studio 2015 project

### ISSUE THREAD

**Issue by MuhammadAasharib** [lexborisov/myhtml#80]
Hi,
Can this library be included in VS2015?? This is causing a lot of errors when i include it in VS 2015 project.

**Comment by lexborisov** [comment]
Hi!

This project can be built as a library with cmake. Use [cmake](https://cmake.org/download/) for create the VS Project by [CMakeLists.txt file](https://github.com/lexborisov/myhtml/blob/master/projects/CMakeLists.txt) in the [project directory](https://github.com/lexborisov/myhtml/blob/master/projects/)

After cmake creates VS Project you can build him for create the library.

for help:
[linking library](http://www.steptools.com/support/stdev_docs/help/settings_vc11.html)
[use dll in vs](http://stackoverflow.com/questions/495795/how-do-i-use-a-third-party-dll-file-in-visual-studio-c)

**Comment by MuhammadAasharib** [comment]
OK THANKS!

**Comment by lexborisov** [comment]
You're welcome!
You coped with the problem? It work?

**Comment by MuhammadAasharib** [comment]
Yeah i coped with problem. But i followed some other steps.
