### ISSUE TITLE
Can't parse a complete <p> tag using if there are hyperlinks within the paragraph.

### ISSUE THREAD

**Issue by mranon0007** [lexborisov/myhtml#81]
I used the following approach to get the text of paragraphs from an html page but the complete paragraph isn't parsed if there are hyperlinks within the paragraph.
```
myhtml_collection_t *collection = myhtml_get_nodes_by_tag_id(tree, NULL, MyHTML_TAG_A, NULL);
myhtml_tree_node_t *text_node = myhtml_node_child(collection->list[0]);
const char* text = myhtml_node_text(text_node, NULL);
```
I went through the wiki but couldn't find anything useful. It'll be great if you can improve the documentation.

**Comment by lexborisov** [comment]
Hi!
You want to get only the text of the ```<p>``` tag?
Unfortunately, the documentation everything is bad - it simply does not exist.

I'm trying to somehow solve this problem, but I only one. Now I'm doing html rendering — [Modest](https://github.com/lexborisov/Modest).

If you describe your problem with examples, then I will help you!

Thank you for writing!

**Comment by mranon0007** [comment]
Thanks for your quick reply. I am trying to understand the structure of parsing. For example
`myhtml_collection_t *collection = myhtml_get_nodes_by_tag_id(tree, NULL, MyHTML_TAG_P, NULL);`
gives us a struct with a list of all the nodes containing the data of `<p>` tags. What happens when there's a `<a>` or `<span>` tag within the `<p>` tag? How does the `struct collection` handle it?

**Comment by mranon0007** [comment]
Sorry for asking too many questions but as you said yourself, there isn't a lot of documentations.
I was going through the examples and found 2 examples:
`get_title_low_level`
`get_title_high_level`
I saw both the examples and both of them were using different header files, what is the difference in both of them?

I am also trying to access a `child` using `collection->list[i]->child` but it gives an error:
`left of '->child' must point to class/struct/union/generic type`
I included `myhtml/tree.h` file along with `myhtml/api.h` file but the compiler won't compile because of redefinition of funcitons.

**Comment by lexborisov** [comment]
It's okay, you can safely ask questions.

High level API do not access to structures. All actions are done through api.h.
If you include ```myhtml/api.h``` you cat not include any other ```myhtml``` header files. In other words, only ```myhtml/api.h``` or any other ```myhtml``` headers (```myhtml/myhtml.h, myhtml/tree.h```)

For example:
if use ```myhtml/api.h```:
```C
myhtml_tree_node_t *child = myhtml_node_child(node);
```
or use ```myhtml/myhtml.h and myhtml/tree.h``` (not together with ```api.h```)
```C
myhtml_tree_node_t *child = node->child;
```

In other words, the high and low level api.

**Comment by lexborisov** [comment]
We have ```HTML```:
```HTML
<p id="1"><a>blah blah blah
<p id="2"><span>oh, my...
<p id="3">some text
```

After parsing we can get all ```<p>``` elements:
```C
myhtml_collection_t *list_of_p = myhtml_get_nodes_by_tag_id(tree, NULL, MyHTML_TAG_P, NULL);

for(size_t i = 0; i < list_of_p->length; i++)
{
    myhtml_string_raw_t str = {0};
    
    myhtml_serialization(tree, list_of_p->list[i], str);
    printf("%s\n", str.data);
    
    myhtml_string_raw_destroy(&str, false);
}
```

We receive only the pointers to the nodes of the tree.
```HTML
<p id="1"> — list_of_p->list[0]
    <a>blah blah blah
<p id="2"> — list_of_p->list[1]
    <span>oh, my...
<p id="3"> — list_of_p->list[2]
    some text
```

That is, nothing is copied. You can:
```C
/* print  blah blah blah*/
printf("%s\n", list_of_p->list[0]->child->child->token->str.data);
```

You should also understand that:
```HTML
<p id="1"><a>blah blah blah
```
or
```HTML
<p id="1">
<a>blah blah blah
```
the result will be different trees:
```HTML
<p id="1">
    <a>
        text: blah blah blah
```
and
```HTML
<p id="1">
    text: \n
    <a>
        text: blah blah blah
```

**Comment by mranon0007** [comment]
Ok so this is my html:
`<body>
    <p>This is<a href="http://www.xyxy.com/section/realestate">LINK</a>Here</p>
</body>`

I tried the following code which you mentioned above:

`myhtml_collection_t *list_of_p = myhtml_get_nodes_by_tag_id(tree, NULL, MyHTML_TAG_P, NULL);

for(size_t i = 0; i < list_of_p->length; i++)
{
    myhtml_string_raw_t str = {0};
    
    myhtml_serialization(tree, list_of_p->list[i], &str);
    printf("%s\n", str.data);
    
    myhtml_string_raw_destroy(&str, false);
}`

Output of the above code is: 
`<p>This is<a href="http://www.xyxy.com/section/realestate">LINK</a>Here</p>`.

Is there any way to strip off the tags and just get the text? 
I want the following output: 
`This is LINK Here`

I tried to use the following method:

`	// parse html
	myhtml_collection_t *collection = myhtml_get_nodes_by_tag_id(tree, NULL, MyHTML_TAG_P, NULL);

	for (int i = 0; i < collection->length; i++) {
			myhtml_tree_node_t *text_node = collection->list[i]->child;

			const char* text = myhtml_node_text(text_node, NULL);

			if (text) {
				printf("%s\n", text);
				cout << endl << endl;
			}
			
//Loop to check for Childs.
			for (myhtml_tree_node_t *j_node = text_node; j_node->child != NULL ; j_node = j_node->next) {
				if (j_node) {
					const char* text = myhtml_node_text(j_node, NULL);

					if (text) {
						printf("%s\n", text);
						cout << endl << endl;
					}

				}
			}
}`

If I am right, shouldn't the <a> tag be a child of <p> in the case of the HTML data provided above? But I get the following output:
`This is`
Why is the `j_node->child == NULL` even though there is an <a> tag within the <p> Tag?

**Comment by lexborisov** [comment]
Your ```HTML``` after parse (use ```myhtml_tree_print_node_children(tree, tree->document, stdout, 0);```):
```HTML
<html>
	<head>
	<body>
		<-text>: 
    
		<p>
			<-text>: This is 
			<a href="http://www.xyxy.com/section/realestate">
				<-text>: LINK
			<-text>:  Here
		<-text>: 

```

There are three ways to receive only text:
**First**
```C
myhtml_collection_t *coll_p = myhtml_get_nodes_by_tag_id(tree, NULL, MyHTML_TAG_P, NULL);
myhtml_collection_t *all_text_nodes = NULL;
    
for (size_t i = 0; i < coll_p->length; i++) {
    all_text_nodes = myhtml_get_nodes_by_tag_id_in_scope(tree, all_text_nodes, coll_p->list[i], MyHTML_TAG__TEXT, NULL);
    
    printf("Text in <P> element #%zu:\n", i);
    for (size_t j = 0; j < all_text_nodes->length; j++) {
        const char* text = myhtml_node_text(all_text_nodes->list[j], NULL);
        printf("%s", text);
    }
    
    myhtml_collection_clean(all_text_nodes);
}

myhtml_collection_destroy(coll_p);
myhtml_collection_destroy(all_text_nodes);
```

**Secondary**
```C
void myhtml_print_text_without_recursion(myhtml_tree_t* tree, myhtml_tree_node_t* scope_node)
{
    myhtml_tree_node_t* node = scope_node;
    
    while(node) {
        if(node->tag_id == MyHTML_TAG__TEXT) {
            const char* text = myhtml_node_text(node, NULL);
            printf("%s", text);
        }
        
        if(node->child)
            node = node->child;
        else {
            while(node != scope_node && node->next == NULL) {
                node = node->parent;
            }
            
            if(node == scope_node)
                return;
            
            node = node->next;
        }
    }
}

myhtml_collection_t *coll_p = myhtml_get_nodes_by_tag_id(tree, NULL, MyHTML_TAG_P, NULL);
for (size_t i = 0; i < coll_p->length; i++) {
    printf("Text in <P> element #%zu:\n", i);
    myhtml_print_text_without_recursion(tree, coll_p->list[i]);
}
myhtml_collection_destroy(coll_p);
```

**Third**
```C
void myhtml_print_text_with_recursion(myhtml_tree_t* tree, myhtml_tree_node_t* scope_node)
{
    if(scope_node->tag_id == MyHTML_TAG__TEXT) {
        const char* text = myhtml_node_text(scope_node, NULL);
        printf("%s", text);
    }
    
    if(scope_node->child)
        myhtml_print_text_with_recursion(tree, scope_node->child);
    if(scope_node->next)
        myhtml_print_text_with_recursion(tree, scope_node->next);
}

myhtml_collection_t *coll_p = myhtml_get_nodes_by_tag_id(tree, NULL, MyHTML_TAG_P, NULL);
for (size_t i = 0; i < coll_p->length; i++) {
    printf("Text in <P> element #%zu:\n", i);
    myhtml_print_text_without_recursion(tree, coll_p->list[i]);
}
myhtml_collection_destroy(coll_p);
```

I would use the second method.

**Comment by mranon0007** [comment]
Thanks a lot, really appreciate such a detailed answer :+1:  
Just one more question, what does `myhtml_serialization()` do?

**Comment by lexborisov** [comment]
```myhtml_serialization_*(...)``` It makes serialization exactly as required by the [specification](https://html.spec.whatwg.org/multipage/syntax.html#serialising-html-fragments).

Just go through the text up to parents. Some like:
```C
while(node) {
    if(node->tag_id == MyHTML_TAG_P) {
        /* do some */
        break;
    }

    node = node->parent;
}
```

**Comment by mranon0007** [comment]
Thanks a lot for such detailed answer. The examples help me to understand the different functions.
I hope I am not taking a lot of your time, I have another question. I have to extract the URL of a webpage where the URL stored in 
````
<head>
meta property="og:url" content="http://xyz.com.com"/>
</head>
```
How can the URL be extracted ? Thanks alot

**Comment by lexborisov** [comment]
See [example](https://github.com/lexborisov/myhtml/blob/master/examples/print_tree_high_level.c#L73) and see description in [API](https://github.com/lexborisov/myhtml/blob/master/include/myhtml/api.h)
