### ISSUE TITLE
Is myhtml able to support document.write?

### ISSUE THREAD

**Issue by tbodt** [lexborisov/myhtml#87]
I'm considering using myhtml in a custom browser I'm making, and I'm wondering about document.write. Does it support pausing parsing when it sees a script element and inserting more markup at the insertion point?

**Comment by lexborisov** [comment]
Hi!
No, MyHTML does not support document.write. It will be in [Modest](https://github.com/lexborisov/Modest)

Thanks for the question!

**Comment by tbodt** [comment]
Is document.write support going to be added to MyHTML so that Modest can implement it?

**Comment by lexborisov** [comment]
No, the whole development is now conducted only in Modest. These only go sync from there. MyHTML it is only full HTML parser.
