### ISSUE TITLE
Before Release 3.0.0

### ISSUE THREAD

**Issue by lexborisov** [lexborisov/myhtml#88]
For anyone interested in, please, see [change log](https://github.com/lexborisov/myhtml/blob/master/CHANGELOG.md)

I had to break the current api. Current changes eliminates the unnecessary use tree (myhtml_tree_t) and allow you to receive current tree from any node.
Now, for many of the functions you do not need to pass a tree. What greatly facilitate further development.

Sorry for the broken API, but all changes are made to the best!

Thanks!

**Comment by kostya** [comment]
just tested in my project, seems no bugs 👍 .

questions:
1) when encoding extracted from meta tag, is it use some normalization algorithm? (i use this https://github.com/kostya/encoding_name)
2) if not, would be nice if method `myhtml_encoding_prescan_stream_to_determine_encoding` return encoding string also, to use it my normalization algorithm.

**Comment by lexborisov** [comment]
Hi!

1) Yes, I use encoding table for normalize extracted encoding name. See [specification part](https://encoding.spec.whatwg.org/#concept-encoding-get)
2) Only as a separate function. We must follow the specifications to work exactly like modern browsers. For getting encoding from HTTP Header you can use:
```C
bool myhtml_encoding_algorithm_extracting_character_encoding_from_meta_element(const char *data, size_t data_size, myhtml_encoding_t *encoding)
```
this function find ```charset``` in string and try to get encoding. Before the release I rename it and add a public api.

Thanks!
