### ISSUE TITLE
encoding bug?

### ISSUE THREAD

**Issue by kostya** [lexborisov/myhtml#89]
if i change in  https://github.com/lexborisov/myhtml/blob/master/examples/print_tree_high_level.c#L154 line to:
```
myhtml_parse(tree, MyHTML_ENCODING_WINDOWS_1251, res.html, res.size);
```

and run with:
```
<html><head><meta charset="cp1251"></head><body><div>����</div></body></html>
```

output is:
./print_tree_high_level 2.html
```
<html>
	<head>
		<meta charset="cp1251">
	<body>
		<div>
			<-text>: ُàُà
		<-text>: 
```

but if i run it with iconv, encoding is ok:
```
cat 2.html | iconv -f cp1251
<html><head><meta charset="cp1251"></head><body><div>хаха</div></body></html>
```

also detect_encoding_high_level, output:
```
./detect_encoding_high_level 2.html 
I could not identify character encoding
```

**Comment by lexborisov** [comment]
1) You can source files? I test right now, works fine
2) For detect encoding by meta tag use example ```detect_encoding_in_meta_high_level```. Too few characters to define by trigrams (```detect_encoding_high_level ```). Detecting character encoding by trigrams an additional method, it is not described in the specification.

```bash
alexanderborisov$ bin/detect_encoding_in_meta_high_level /new/C-git/2.html 
Encoding: WINDOWS-1252
```

**Comment by kostya** [comment]
https://gist.github.com/kostya/7d7bcd3501287e32efb98db4ae3657bc

**Comment by lexborisov** [comment]
Oh, I am broken encoding mapping. 
Thank you! I will add the encodings check in tests.
