### ISSUE TITLE
bug chunk parsing from buffer

### ISSUE THREAD

**Issue by kostya** [lexborisov/myhtml#90]
```c
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <myhtml/api.h>

int main(int argc, const char * argv[])
{
    char html[][64] = {
        "<html><bod",
        "y><div cla",
        "ss=A>ooo</",
        "div></body",
        "></html>",
        "\0"
    };
    
    // basic init
    myhtml_t* myhtml = myhtml_create();
    myhtml_init(myhtml, MyHTML_OPTIONS_DEFAULT, 1, 0);
    
    // init tree
    myhtml_tree_t* tree = myhtml_tree_create();
    myhtml_tree_init(tree, myhtml);
    
    myhtml_encoding_set(tree, MyHTML_ENCODING_UTF_8);

    char buffer[64];
    
    for(size_t i = 0; html[i][0]; i++)
    {
        //copy to buffer
        for (int j = 0; j <= strlen(html[i]); j++) { buffer[j] = html[i][j]; }
        printf("Parse chunk: %s\n", buffer);
        
        // parse html
        myhtml_parse_chunk(tree, buffer, strlen(buffer));
    }
    
    // call to the end
    myhtml_parse_chunk_end(tree);
    
    // // print fragment
    myhtml_tree_print_node_children(tree, myhtml_tree_get_document(tree), stdout, 0);
    
    // release resources
    myhtml_tree_destroy(tree);
    myhtml_destroy(myhtml);
    
    return 0;
}
```

```
Parse chunk: <html><bod
Parse chunk: y><div cla
Parse chunk: ss=A>ooo</
Parse chunk: div></body
Parse chunk: ></html>
<html>
       	<head>
       	<body>
       		<clay>
       			<div o</ss="A">
       				<-text>: /bo
```

expected class but got `o</ss`

**Comment by lexborisov** [comment]
Hi!
No, everything is working correctly! The parser does not copy the input buffer. You must save the buffer to the end of parsing! 
In your example you have it constantly overwritten.

Perhaps the time has come to write documentation! :)

Thank you for writing!

**Comment by kostya** [comment]
hm, i expect this to work, because this is usual, when read from socket, using self-overwritted buffer is normal.

**Comment by lexborisov** [comment]
Just luck, if chunk is big and split in "right places" he's just working fine. But, you should not do, overwrite buffer may cause an infinite loop. 
I do not see any reason to copy an input buffer, it is necessary only to parse.

**Comment by lexborisov** [comment]
I can add option ```myhtml_parser_save_incomming_buffer``` or something like that. The buffer will be stored until the end of parsing.

**Comment by kostya** [comment]
there is no actually a problem, i can save buffers by myself: https://github.com/kostya/myhtml/blob/master/src/myhtml/parser.cr#L55

**Comment by lexborisov** [comment]
Excellent! Thank you for writing!
