### ISSUE TITLE
Готовые пакеты

### ISSUE THREAD

**Issue by layershifter** [lexborisov/myhtml#99]
@lexborisov Во-первых, спасибо за проделанный титанический труд :+1: 

Есть одна проблема, библиотеку хотелось бы иметь в пакетах для различных дистрибутивов, так как тянуть инструменты сборки на production не хочется.

Всем понятно, что вручную этого делать никто не будет :smile: Я использую [packpack](https://github.com/packpack/packpack), заданным требованиям он отвечает.

Если к этому есть интерес, я бы мог открыть PR реализующий это.

**Comment by lexborisov** [comment]
Привет и спасибо!
Присылай PR посмотрим, с инструкцией на английском :). Пакеты нужны — это безусловно. Раньше можно было собирать их с помощью cmake. Но с последними обновлениями он был выпилен из-за неудобства поддержки.

Спасибо!
